/**
 * Player-facing text of the meta layer, Korean (friendly 해요체) and English. Numbers are never
 * typed in: `{n}`-style placeholders are filled from the data tables. Registered at import time.
 */
import { addStrings } from '@/core/i18n';
// Registers the rarity, unit and chapter names the texts below point at (`rarity.*`, `unit.*.name`, `chapter.*.name`).
import '@/game/data/strings';
import { IAP_SPECS } from './data/catalog';

const ko: Record<string, string> = {
  // currencies and chests
  'meta.currency.gold': '골드',
  'meta.currency.gems': '보석',
  'meta.currency.tickets': '소탕권',
  'meta.chest.wooden': '나무 상자',
  'meta.chest.silver': '은 상자',
  'meta.chest.gold': '금 상자',
  'meta.reward.gold': '골드 {n}',
  'meta.reward.gems': '보석 {n}',
  'meta.reward.tickets': '소탕권 {n}장',
  'meta.reward.chest': '{name} {n}개',
  'meta.reward.wild': '만능 카드({rarity}) {n}장',
  'meta.reward.card': '{unit} 카드 {n}장',

  // odds screen
  'meta.odds.head': '{chest}, 카드 {n}장.',
  'meta.odds.row': '{rarity} {pct}',
  'meta.odds.wild': '카드의 {pct}는 같은 등급 아무 고양이에게나 쓰는 만능 카드예요.',
  'meta.odds.guarantee': '{rarity} 이상 {n}장은 꼭 들어 있어요.',
  'meta.odds.guaranteeTop': '{rarity} {n}장은 꼭 들어 있어요.',
  'meta.odds.pity': '금 상자 {every}개째마다 가장 레벨이 낮은 {rarity}(지금: {unit}) 카드 {n}장이 더 들어요. ({counter}/{every})',
  'meta.odds.version': '확률표 v{v}',
  'meta.odds.title': '상자 확률',

  // errors (toasts)
  'meta.err.not_enough_gold': '골드가 모자라요.',
  'meta.err.not_enough_gems': '보석이 모자라요.',
  'meta.err.not_enough_tickets': '소탕권이 없어요.',
  'meta.err.not_enough_cards': '카드가 모자라요.',
  'meta.err.max_level': '이미 최고 레벨이에요.',
  'meta.err.locked': '아직 열리지 않았어요.',
  'meta.err.not_ready': '아직 받을 수 없어요.',
  'meta.err.already_claimed': '이미 받았어요.',
  'meta.err.limit_reached': '오늘은 더 할 수 없어요.',
  'meta.err.ad_failed': '광고를 끝까지 보지 않아서 보상이 없어요.',
  'meta.err.unavailable': '지금은 할 수 없어요. 잠시 뒤에 다시 해 보세요.',
  'meta.err.invalid': '올바르지 않은 요청이에요.',
  'meta.err.invalid_code': '냥이 코드가 올바르지 않아요. 처음부터 끝까지 다시 붙여 넣어 보세요.',
  'meta.err.corrupt_code': '냥이 코드가 중간에 잘렸거나 글자가 바뀐 것 같아요.',
  'meta.err.newer_version': '더 새로운 버전에서 만든 코드예요. 게임을 업데이트해 주세요.',
  'meta.err.clock_frozen': '기기 시계가 바뀐 것 같아요. 게임을 다시 켜면 시간 보상을 받을 수 있어요.',
  'meta.err.already_owned': '이미 가지고 있어요.',
  'meta.err.not_owned': '아직 가지고 있지 않아요.',
  'meta.err.nothing_to_claim': '받을 보상이 없어요.',
  'meta.err.not_cleared': '먼저 클리어한 단계만 소탕할 수 있어요.',
  'meta.err.run_active': '끝나지 않은 판이 있어요.',

  // toasts
  'meta.toast.claimed': '받았어요!',
  'meta.toast.levelUp': '{unit}이(가) {level}레벨이 됐어요!',
  'meta.toast.restored': '냥이 코드를 불러왔어요.',

  // unlocks
  'meta.feature.speed2x': '2배속',
  'meta.feature.cats': '고양이',
  'meta.feature.patrol': '순찰',
  'meta.feature.missions': '미션',
  'meta.feature.shop': '상점',
  'meta.feature.treat': '오늘의 간식',
  'meta.feature.piggy': '저금통',
  'meta.feature.cosmetics': '꾸미기',
  'meta.feature.pass': '시즌 패스',
  'meta.feature.daily': '일일 도전',
  'meta.feature.sweep': '소탕',
  'meta.feature.cup': '주간 컵',
  'meta.feature.endless': '무한 모드',
  'meta.feature.dungeon': '골드 던전',
  'meta.feature.speed3x': '3배속',
  'meta.unlock.runs': '{n}판을 마치면 열려요.',
  'meta.unlock.level': '계정 {n}레벨이 되면 열려요.',
  'meta.unlock.chapter': '{chapter}을(를) 클리어하면 열려요.',
  'meta.unlock.butler': '집사 패스가 있으면 쓸 수 있어요.',

  // missions
  'meta.mission.d_runs': '{n}판 플레이하기',
  'meta.mission.d_merges': '고양이 {n}번 합치기',
  'meta.mission.d_bosses': '보스·정예 {n}마리 처치하기',
  'meta.mission.d_relics': '장난감 {n}개 얻기',
  'meta.mission.d_wins': '승리 {n}번 하기',
  'meta.mission.w_runs': '이번 주에 {n}판 플레이하기',
  'meta.mission.w_merges': '이번 주에 {n}번 합치기',
  'meta.mission.w_bosses': '이번 주에 보스·정예 {n}마리 처치하기',
  'meta.mission.w_wins': '이번 주에 {n}번 승리하기',
  'meta.mission.w_chests': '일일 미션 상자 {n}번 받기',
  'meta.mission.points': '{points}/{need}점',
  'meta.mission.dailyChest': '100점을 모으면 상자가 열려요.',
  'meta.mission.weeklyChest': '주간 미션을 모두 끝내면 금 상자를 줘요.',

  // offers and snacks
  'meta.offer.revive': '계속하기',
  'meta.offer.result_double': '보상 2배',
  'meta.offer.chest_skip': '상자 바로 받기',
  'meta.offer.relic_reroll': '다시 뽑기',
  'meta.offer.start_snack': '출발 간식',
  'meta.snack.fish': '생선 +{n}',
  'meta.snack.purr': '골골 +{n}',
  'meta.snack.rare_summon': '첫 소환은 희귀 이상',
  'meta.treat.title': '오늘의 간식',
  'meta.treat.slot': '간식 {n}',

  // shop, calendar, pass, cup, daily, piggy
  'meta.shop.free': '무료',
  'meta.shop.cards': '카드 묶음',
  'meta.shop.wild': '만능 카드 묶음',
  'meta.shop.gem': '보석 특가',
  'meta.calendar.day': '{n}일째',
  'meta.calendar.comeback': '돌아온 걸 환영해요! 은 상자와 긴 순찰을 준비했어요.',
  'meta.pass.free': '무료',
  'meta.pass.premium': '프리미엄',
  'meta.pass.tier': '{n}단계',
  'meta.cup.tier': '합계 {n}웨이브',
  'meta.endless.tier': '{n}웨이브',
  'meta.daily.title': '일일 도전',
  'meta.daily.code': '오늘의 코드 {code}',
  'meta.piggy.title': '저금통',
  'meta.piggy.free': '{days}일 뒤에는 결제 없이 {n}개를 꺼낼 수 있어요.',
  'meta.backup.title': '냥이 코드',
  'meta.backup.help': '이 코드를 다른 기기에 붙여 넣으면 진행 상황을 옮길 수 있어요.',

  // cosmetics
  'meta.cos.rug_default': '기본 러그',
  'meta.cos.rug_ch1': '거실 러그',
  'meta.cos.rug_ch2': '주방 러그',
  'meta.cos.rug_ch3': '욕실 러그',
  'meta.cos.rug_ch4': '마당 러그',
  'meta.cos.rug_ch5': '병원 러그',
  'meta.cos.rug_gem1': '딸기 러그',
  'meta.cos.rug_gem2': '구름 러그',
  'meta.cos.rug_gem3': '별밤 러그',
  'meta.cos.rug_baby': '아기 고양이 러그',
  'meta.cos.rug_butler': '집사 러그',
  'meta.cos.rug_calendar': '출석 러그',
  'meta.cos.rug_season': '시즌 러그',
  'meta.cos.fx_default': '기본 소환 이펙트',
  'meta.cos.fx_gem1': '꽃잎 소환',
  'meta.cos.fx_gem2': '별똥별 소환',
  'meta.cos.fx_gem3': '비눗방울 소환',
};

const en: Record<string, string> = {
  'meta.currency.gold': 'Gold',
  'meta.currency.gems': 'Gems',
  'meta.currency.tickets': 'Sweep tickets',
  'meta.chest.wooden': 'Wooden chest',
  'meta.chest.silver': 'Silver chest',
  'meta.chest.gold': 'Gold chest',
  'meta.reward.gold': '{n} gold',
  'meta.reward.gems': '{n} gems',
  'meta.reward.gems.one': '{n} gem',
  'meta.reward.tickets': '{n} sweep tickets',
  'meta.reward.tickets.one': '{n} sweep ticket',
  'meta.reward.chest': '{n} x {name}',
  'meta.reward.wild': '{n} wild cards ({rarity})',
  'meta.reward.wild.one': '{n} wild card ({rarity})',
  'meta.reward.card': '{n} {unit} cards',
  'meta.reward.card.one': '{n} {unit} card',

  'meta.odds.head': '{chest}, {n} cards.',
  'meta.odds.row': '{rarity} {pct}',
  'meta.odds.wild': '{pct} of the cards are wild cards that work on any cat of the same rarity.',
  'meta.odds.guarantee': 'At least {n} {rarity} cards or better in every chest.',
  'meta.odds.guarantee.one': 'At least {n} {rarity} card or better in every chest.',
  'meta.odds.guaranteeTop': 'At least {n} {rarity} cards in every chest.',
  'meta.odds.guaranteeTop.one': 'At least {n} {rarity} card in every chest.',
  'meta.odds.pity': 'Every {every}th gold chest adds {n} cards of your lowest-level {rarity} (now: {unit}). ({counter}/{every})',
  'meta.odds.version': 'Odds table v{v}',
  'meta.odds.title': 'Chest odds',

  'meta.err.not_enough_gold': 'Not enough gold.',
  'meta.err.not_enough_gems': 'Not enough gems.',
  'meta.err.not_enough_tickets': 'No sweep tickets left.',
  'meta.err.not_enough_cards': 'Not enough cards.',
  'meta.err.max_level': 'Already at the top level.',
  'meta.err.locked': 'Not unlocked yet.',
  'meta.err.not_ready': 'Not ready yet.',
  'meta.err.already_claimed': 'Already claimed.',
  'meta.err.limit_reached': 'No more of these today.',
  'meta.err.ad_failed': 'The ad was not finished, so there is no reward.',
  'meta.err.unavailable': 'Not available right now. Please try again in a moment.',
  'meta.err.invalid': 'That request is not valid.',
  'meta.err.invalid_code': 'That Meow Code is not valid. Try pasting the whole code again.',
  'meta.err.corrupt_code': 'That Meow Code looks cut off or changed.',
  'meta.err.newer_version': 'This code comes from a newer version. Please update the game.',
  'meta.err.clock_frozen': 'The device clock seems to have changed. Restart the game to get time-based rewards.',
  'meta.err.already_owned': 'You already have this.',
  'meta.err.not_owned': 'You do not have this yet.',
  'meta.err.nothing_to_claim': 'Nothing to claim.',
  'meta.err.not_cleared': 'You can only sweep stages you have already cleared.',
  'meta.err.run_active': 'There is a run that has not finished.',

  'meta.toast.claimed': 'Claimed!',
  'meta.toast.levelUp': '{unit} reached level {level}!',
  'meta.toast.restored': 'Meow Code restored.',

  'meta.feature.speed2x': '2x speed',
  'meta.feature.cats': 'Cats',
  'meta.feature.patrol': 'Patrol',
  'meta.feature.missions': 'Missions',
  'meta.feature.shop': 'Shop',
  'meta.feature.treat': "Today's Treat",
  'meta.feature.piggy': 'Piggy bank',
  'meta.feature.cosmetics': 'Cosmetics',
  'meta.feature.pass': 'Season pass',
  'meta.feature.daily': 'Daily challenge',
  'meta.feature.sweep': 'Sweep',
  'meta.feature.cup': 'Weekly cup',
  'meta.feature.endless': 'Endless mode',
  'meta.feature.dungeon': 'Gold dungeon',
  'meta.feature.speed3x': '3x speed',
  'meta.unlock.runs': 'Unlocks after {n} runs.',
  'meta.unlock.runs.one': 'Unlocks after {n} run.',
  'meta.unlock.level': 'Unlocks at account level {n}.',
  'meta.unlock.chapter': 'Unlocks when you clear {chapter}.',
  'meta.unlock.butler': 'Available with the Butler Pass.',

  'meta.mission.d_runs': 'Play {n} runs',
  'meta.mission.d_merges': 'Merge cats {n} times',
  'meta.mission.d_bosses': 'Defeat {n} bosses or elites',
  'meta.mission.d_relics': 'Collect {n} toys',
  'meta.mission.d_wins': 'Win {n} run',
  'meta.mission.w_runs': 'Play {n} runs this week',
  'meta.mission.w_merges': 'Merge {n} times this week',
  'meta.mission.w_bosses': 'Defeat {n} bosses or elites this week',
  'meta.mission.w_wins': 'Win {n} runs this week',
  'meta.mission.w_chests': 'Claim the daily mission chest {n} times',
  'meta.mission.points': '{points}/{need} points',
  'meta.mission.dailyChest': 'Collect 100 points to open the chest.',
  'meta.mission.weeklyChest': 'Finish every weekly mission for a gold chest.',

  'meta.offer.revive': 'Continue',
  'meta.offer.result_double': 'Double reward',
  'meta.offer.chest_skip': 'Skip the wait',
  'meta.offer.relic_reroll': 'Reroll',
  'meta.offer.start_snack': 'Pre-run snack',
  'meta.snack.fish': '+{n} fish',
  'meta.snack.purr': '+{n} purr',
  'meta.snack.rare_summon': 'First summon is rare or better',
  'meta.treat.title': "Today's Treat",
  'meta.treat.slot': 'Treat {n}',


  'meta.shop.free': 'Free',
  'meta.shop.cards': 'Card lot',
  'meta.shop.wild': 'Wild card lot',
  'meta.shop.gem': 'Gem deal',
  'meta.calendar.day': 'Day {n}',
  'meta.calendar.comeback': 'Welcome back! A silver chest and a long patrol are waiting.',
  'meta.pass.free': 'Free',
  'meta.pass.premium': 'Premium',
  'meta.pass.tier': 'Tier {n}',
  'meta.cup.tier': 'Total {n} waves',
  'meta.endless.tier': 'Wave {n}',
  'meta.daily.title': 'Daily challenge',
  'meta.daily.code': "Today's code {code}",
  'meta.piggy.title': 'Piggy bank',
  'meta.piggy.free': 'After {days} days you can take {n} gems out for free.',
  'meta.piggy.free.one': 'After {days} day you can take {n} gems out for free.',
  'meta.backup.title': 'Meow Code',
  'meta.backup.help': 'Paste this code on another device to move your progress.',

  'meta.cos.rug_default': 'Default rug',
  'meta.cos.rug_ch1': 'Living room rug',
  'meta.cos.rug_ch2': 'Kitchen rug',
  'meta.cos.rug_ch3': 'Bathroom rug',
  'meta.cos.rug_ch4': 'Garden rug',
  'meta.cos.rug_ch5': 'Clinic rug',
  'meta.cos.rug_gem1': 'Strawberry rug',
  'meta.cos.rug_gem2': 'Cloud rug',
  'meta.cos.rug_gem3': 'Starry night rug',
  'meta.cos.rug_baby': 'Kitten rug',
  'meta.cos.rug_butler': 'Butler rug',
  'meta.cos.rug_calendar': 'Calendar rug',
  'meta.cos.rug_season': 'Season rug',
  'meta.cos.fx_default': 'Default summon effect',
  'meta.cos.fx_gem1': 'Petal summon',
  'meta.cos.fx_gem2': 'Shooting star summon',
  'meta.cos.fx_gem3': 'Bubble summon',
};

const koDesc: Record<string, string> = {
  baby_cat_pack: '처음 한 번만 살 수 있어요. 보석, 은 상자, 러그 스킨이 들어 있어요.',
  starter_pack: '한 번만 살 수 있는 성장 묶음이에요.',
  growth_pack: '한 번만 살 수 있는 큰 성장 묶음이에요.',
  butler_pass: '3배속, 광고 없는 보상 2배·상자 건너뛰기·순찰 2배, 순찰 12시간, 소탕권 매일 +3. 판 안의 이득은 없어요.',
  season_pass: '30일 동안 프리미엄 보상 줄을 열어요.',
  gem_pass: '바로 보석 200개, 30일 동안 매일 30개를 받아요.',
  piggy_bank: '판마다 쌓인 보너스 보석을 한 번에 꺼내요.',
  gems_260: '보석 묶음이에요.',
  gems_680: '보석 묶음이에요.',
  gems_1450: '보석 묶음이에요.',
  gems_4600: '보석 묶음이에요.',
};

const enDesc: Record<string, string> = {
  baby_cat_pack: 'One-time offer with gems, a silver chest and a rug skin.',
  starter_pack: 'A one-time growth bundle.',
  growth_pack: 'A bigger one-time growth bundle.',
  butler_pass: '3x speed, ad-free double reward, chest skip and double patrol, 12 h patrol, +3 sweep tickets a day. Nothing that helps inside a run.',
  season_pass: 'Opens the premium reward row for 30 days.',
  gem_pass: '200 gems now and 30 gems every day for 30 days.',
  piggy_bank: 'Take out all the bonus gems that built up run by run.',
  gems_260: 'A bundle of gems.',
  gems_680: 'A bundle of gems.',
  gems_1450: 'A bundle of gems.',
  gems_4600: 'A bundle of gems.',
};

for (const s of IAP_SPECS) {
  ko['meta.iap.' + s.id + '.name'] = s.name.ko;
  en['meta.iap.' + s.id + '.name'] = s.name.en;
  ko['meta.iap.' + s.id + '.desc'] = koDesc[s.id] ?? '';
  en['meta.iap.' + s.id + '.desc'] = enDesc[s.id] ?? '';
}

addStrings('ko', ko);
addStrings('en', en);
