/** Player-facing lines of the system screens (settings, calendar, automatic popups), ko (해요체) and en. Keys: rt.common.*, rt.sys.* */
import { addStrings } from '@/core/i18n';

addStrings('ko', {
  'rt.common.claim': '받기',
  'rt.common.claimed': '받았어요',
  'rt.common.ok': '좋아요',
  'rt.common.later': '나중에',
  'rt.common.odds': '확률 보기',
  'rt.common.reward': '보상',
  'rt.common.resetsIn': '초기화까지 {time}',

  // settings
  'rt.sys.settings': '설정',
  'rt.sys.section.sound': '소리',
  'rt.sys.section.screen': '화면',
  'rt.sys.section.game': '게임',
  'rt.sys.section.data': '내 기록',
  'rt.sys.music': '음악',
  'rt.sys.sfx': '효과음',
  'rt.sys.shake': '화면 흔들림',
  'rt.sys.shake.full': '보통',
  'rt.sys.shake.reduced': '줄임',
  'rt.sys.shake.off': '끔',
  'rt.sys.flashes': '번쩍임',
  'rt.sys.reduceMotion': '움직임 줄이기',
  'rt.sys.haptics': '진동',
  'rt.sys.numbers': '피해 숫자',
  'rt.sys.numbers.full': '전체',
  'rt.sys.numbers.brief': '간략',
  'rt.sys.numbers.off': '끔',
  'rt.sys.numbers.hint': '간략은 치명타·처치·큰 피해만, 전체는 일반 피해까지 보여요.',
  'rt.sys.quality': '효과 품질',
  'rt.sys.quality.auto': '자동',
  'rt.sys.quality.high': '높음',
  'rt.sys.quality.mid': '보통',
  'rt.sys.quality.low': '낮음',
  'rt.sys.quality.hint': '자동은 기기가 버거울 때 알아서 낮춰요.',
  'rt.sys.lang': '언어',
  'rt.sys.restore': '구매 복원',
  'rt.sys.restore.none': '복원할 구매가 없어요.',
  'rt.sys.restore.done': '구매를 복원했어요.',
  'rt.sys.restore.fail': '복원하지 못했어요. 잠시 뒤에 다시 해 보세요.',
  'rt.sys.version': '버전 {v}',
  'rt.sys.volatile': '이 브라우저 모드에서는 진행 상황이 저장되지 않을 수 있어요.',
  'rt.sys.section.about': '정보',
  'rt.sys.section.test': '테스트',
  'rt.sys.test.hint': '개발용 빌드에서만 보여요. 누르면 바로 받아요.',
  'rt.sys.test.gold': '골드 +{n}',
  'rt.sys.test.gems': '보석 +{n}',
  'rt.sys.test.tickets': '소탕권 +{n}',
  'rt.sys.test.got': '{what}, 받았어요!',
  'rt.sys.test.full': '더 받을 수 없어요.',
  'rt.sys.link.privacy': '개인정보 처리방침',
  'rt.sys.link.terms': '이용약관',
  'rt.sys.link.support': '문의하기',
  'rt.sys.reset': '진행 상황 지우기',
  'rt.sys.reset.hint': '고양이와 보석, 기록을 모두 지우고 처음부터 시작해요.',
  'rt.sys.reset.title1': '진행 상황 지우기',
  'rt.sys.reset.msg1': '고양이, 골드, 보석, 기록이 모두 사라져요. 정말 지울까요?',
  'rt.sys.reset.yes1': '계속하기',
  'rt.sys.reset.title2': '마지막으로 확인해요',
  'rt.sys.reset.msg2': '지운 기록은 되돌릴 수 없어요. 냥이 코드를 보내 두었는지 확인해 주세요.',
  'rt.sys.reset.yes2': '모두 지우기',
  'rt.sys.reset.no': '그만두기',

  // backup code
  'rt.sys.code.title': '냥이 코드',
  'rt.sys.code.export': '코드 보내기',
  'rt.sys.code.import': '코드 불러오기',
  'rt.sys.code.exportHelp': '이 코드를 복사해 두세요. 다른 기기에서 "코드 불러오기"에 붙여 넣으면 진행 상황이 옮겨져요. 코드는 나만 알고 있어요.',
  'rt.sys.code.importHelp': '복사해 둔 냥이 코드를 아래에 붙여 넣어 주세요.',
  'rt.sys.code.copy': '복사하기',
  'rt.sys.code.copied': '복사했어요.',
  'rt.sys.code.copyFail': '복사하지 못했어요. 글자를 길게 눌러 직접 복사해 주세요.',
  'rt.sys.code.paste': '붙여넣기',
  'rt.sys.code.pasteFail': '붙여넣기가 막혀 있어요. 아래 칸을 눌러 직접 붙여 넣어 주세요.',
  'rt.sys.code.check': '확인하기',
  'rt.sys.code.empty': '코드를 먼저 붙여 넣어 주세요.',
  'rt.sys.code.length': '{n}글자',
  'rt.sys.code.placeholder': 'MG1.…',
  'rt.sys.code.previewTitle': '이 코드에는 이런 기록이 있어요',
  'rt.sys.code.level': '계정 레벨',
  'rt.sys.code.gold': '골드',
  'rt.sys.code.gems': '보석',
  'rt.sys.code.chapters': '클리어한 챕터',
  'rt.sys.code.savedAt': '저장한 때',
  'rt.sys.code.warn': '지금 기록은 이 코드로 바뀌어요. 되돌릴 수 없어요.',
  'rt.sys.code.apply': '이 코드로 바꾸기',
  'rt.sys.code.back': '다시 입력',

  // calendar
  'rt.sys.cal.title': '출석 달력',
  'rt.sys.cal.claim': '오늘 받기',
  'rt.sys.cal.done': '오늘은 받았어요',
  'rt.sys.cal.note': '빠져도 괜찮아요. 접속한 날마다 한 칸씩 나아가요.',
  'rt.sys.cal.cycle': '{n}번째 달력',
  'rt.sys.cal.progress': '{n}/{max}일',

  // automatic popups
  'rt.sys.comeback.title': '어서 와요!',
  'rt.sys.comeback.body': '오랜만에 와 줘서 고마워요. 선물 상자를 준비했어요.',
  'rt.sys.comeback.patrol': '순찰 보상을 24시간치까지 모아 뒀어요.',
  'rt.sys.gempass.title': '보석 패스',
  'rt.sys.gempass.body': '오늘의 보석이 기다려요.',
  'rt.sys.gempass.days': '{n}일 남았어요.',
  'rt.sys.level.title': '계정 레벨 {n}!',
  'rt.sys.level.body': '보석을 받았어요.',
  'rt.sys.unlock.title': '새로 열렸어요!',
  'rt.sys.unlock.more': '그리고 {n}가지 더',
  'rt.sys.unlock.go': '보러 가기',
  'rt.sys.feat.speed2x': '전투를 2배 빠르게 볼 수 있어요.',
  'rt.sys.feat.speed3x': '전투를 3배 빠르게 볼 수 있어요.',
  'rt.sys.feat.cats': '고양이를 키우고 레벨을 올려요.',
  'rt.sys.feat.patrol': '순찰 나간 고양이가 골드를 모아 와요.',
  'rt.sys.feat.missions': '미션을 끝내고 상자를 받아요.',
  'rt.sys.feat.shop': '상자와 일일 상점을 만나요.',
  'rt.sys.feat.treat': '광고 한 편에 오늘의 간식을 받아요.',
  'rt.sys.feat.piggy': '판마다 보석이 저금통에 쌓여요.',
  'rt.sys.feat.cosmetics': '러그와 소환 이펙트로 꾸며요.',
  'rt.sys.feat.pass': '단계마다 보상이 쌓이는 시즌 패스예요.',
  'rt.sys.feat.daily': '매일 바뀌는 도전에 나서요.',
  'rt.sys.feat.sweep': '소탕권으로 클리어한 판을 바로 끝내요.',
  'rt.sys.feat.cup': '일일 도전 기록으로 주간 컵 상자를 받아요.',
  'rt.sys.feat.endless': '끝없이 밀려오는 적을 막아요.',
  'rt.sys.feat.dungeon': '하루 두 번, 짧은 판으로 골드를 모아요.',
});

addStrings('en', {
  'rt.common.claim': 'Claim',
  'rt.common.claimed': 'Claimed',
  'rt.common.ok': 'Nice',
  'rt.common.later': 'Later',
  'rt.common.odds': 'See odds',
  'rt.common.reward': 'Reward',
  'rt.common.resetsIn': 'Resets in {time}',

  'rt.sys.settings': 'Settings',
  'rt.sys.section.sound': 'Sound',
  'rt.sys.section.screen': 'Screen',
  'rt.sys.section.game': 'Game',
  'rt.sys.section.data': 'My progress',
  'rt.sys.music': 'Music',
  'rt.sys.sfx': 'Sound effects',
  'rt.sys.shake': 'Screen shake',
  'rt.sys.shake.full': 'Full',
  'rt.sys.shake.reduced': 'Reduced',
  'rt.sys.shake.off': 'Off',
  'rt.sys.flashes': 'Flashes',
  'rt.sys.reduceMotion': 'Reduce motion',
  'rt.sys.haptics': 'Vibration',
  'rt.sys.numbers': 'Damage numbers',
  'rt.sys.numbers.full': 'All',
  'rt.sys.numbers.brief': 'Brief',
  'rt.sys.numbers.off': 'Off',
  'rt.sys.numbers.hint': 'Brief shows crits, kills and big hits; All adds ordinary hits.',
  'rt.sys.quality': 'Effects quality',
  'rt.sys.quality.auto': 'Auto',
  'rt.sys.quality.high': 'High',
  'rt.sys.quality.mid': 'Mid',
  'rt.sys.quality.low': 'Low',
  'rt.sys.quality.hint': 'Auto lowers it by itself when the device struggles.',
  'rt.sys.lang': 'Language',
  'rt.sys.restore': 'Restore purchases',
  'rt.sys.restore.none': 'No purchases to restore.',
  'rt.sys.restore.done': 'Purchases restored.',
  'rt.sys.restore.fail': 'Could not restore. Please try again in a moment.',
  'rt.sys.version': 'Version {v}',
  'rt.sys.volatile': 'Progress may not be saved in this browser mode.',
  'rt.sys.section.about': 'About',
  'rt.sys.section.test': 'Test',
  'rt.sys.test.hint': 'Shown in development builds only. Tap to get it right away.',
  'rt.sys.test.gold': 'Gold +{n}',
  'rt.sys.test.gems': 'Gems +{n}',
  'rt.sys.test.tickets': 'Tickets +{n}',
  'rt.sys.test.got': '{what}: got it!',
  'rt.sys.test.full': 'No room for more.',
  'rt.sys.link.privacy': 'Privacy policy',
  'rt.sys.link.terms': 'Terms of service',
  'rt.sys.link.support': 'Contact support',
  'rt.sys.reset': 'Erase progress',
  'rt.sys.reset.hint': 'Erases your cats, gems and records and starts over.',
  'rt.sys.reset.title1': 'Erase progress',
  'rt.sys.reset.msg1': 'Your cats, gold, gems and records will be gone. Erase everything?',
  'rt.sys.reset.yes1': 'Continue',
  'rt.sys.reset.title2': 'One last check',
  'rt.sys.reset.msg2': 'Erased progress cannot come back. Make sure you saved a Meow Code first.',
  'rt.sys.reset.yes2': 'Erase all',
  'rt.sys.reset.no': 'Keep playing',

  'rt.sys.code.title': 'Meow Code',
  'rt.sys.code.export': 'Export code',
  'rt.sys.code.import': 'Import code',
  'rt.sys.code.exportHelp': 'Copy this code and keep it. Paste it into "Import code" on another device to move your progress. Keep it to yourself.',
  'rt.sys.code.importHelp': 'Paste your Meow Code below.',
  'rt.sys.code.copy': 'Copy',
  'rt.sys.code.copied': 'Copied.',
  'rt.sys.code.copyFail': 'Could not copy. Press and hold the text to copy it yourself.',
  'rt.sys.code.paste': 'Paste',
  'rt.sys.code.pasteFail': 'Pasting is blocked. Tap the box below and paste it yourself.',
  'rt.sys.code.check': 'Check code',
  'rt.sys.code.empty': 'Paste a code first.',
  'rt.sys.code.length': '{n} characters',
  'rt.sys.code.placeholder': 'MG1.…',
  'rt.sys.code.previewTitle': 'This code holds',
  'rt.sys.code.level': 'Account level',
  'rt.sys.code.gold': 'Gold',
  'rt.sys.code.gems': 'Gems',
  'rt.sys.code.chapters': 'Chapters cleared',
  'rt.sys.code.savedAt': 'Saved on',
  'rt.sys.code.warn': 'Your current progress will be replaced by this code. This cannot be undone.',
  'rt.sys.code.apply': 'Replace with this code',
  'rt.sys.code.back': 'Enter again',

  'rt.sys.cal.title': 'Daily calendar',
  'rt.sys.cal.claim': 'Claim today',
  'rt.sys.cal.done': 'Claimed today',
  'rt.sys.cal.note': 'Missing a day is fine. Every day you play moves you one box forward.',
  'rt.sys.cal.cycle': 'Calendar #{n}',
  'rt.sys.cal.progress': 'Day {n}/{max}',

  'rt.sys.comeback.title': 'Welcome back!',
  'rt.sys.comeback.body': 'Thanks for coming back. We saved a chest for you.',
  'rt.sys.comeback.patrol': 'Patrol rewards are saved up for 24 hours.',
  'rt.sys.gempass.title': 'Gem Pass',
  'rt.sys.gempass.body': 'Your gems for today are waiting.',
  'rt.sys.gempass.days': '{n} days left.',
  'rt.sys.level.title': 'Account level {n}!',
  'rt.sys.level.body': 'You got gems.',
  'rt.sys.unlock.title': 'Newly unlocked!',
  'rt.sys.unlock.more': 'and {n} more',
  'rt.sys.unlock.go': 'Take a look',
  'rt.sys.feat.speed2x': 'Watch battles at double speed.',
  'rt.sys.feat.speed3x': 'Watch battles at triple speed.',
  'rt.sys.feat.cats': 'Raise your cats and level them up.',
  'rt.sys.feat.patrol': 'Patrolling cats bring back gold.',
  'rt.sys.feat.missions': 'Finish missions and get chests.',
  'rt.sys.feat.shop': 'Chests and the daily shop.',
  'rt.sys.feat.treat': 'One ad earns today\'s treat.',
  'rt.sys.feat.piggy': 'Bonus gems pile up run by run.',
  'rt.sys.feat.cosmetics': 'Decorate with rugs and summon effects.',
  'rt.sys.feat.pass': 'A season pass with rewards every tier.',
  'rt.sys.feat.daily': 'A new challenge every day.',
  'rt.sys.feat.sweep': 'Finish cleared chapters instantly with tickets.',
  'rt.sys.feat.cup': 'Daily challenge scores earn weekly cup chests.',
  'rt.sys.feat.endless': 'Hold off enemies that never stop.',
  'rt.sys.feat.dungeon': 'Two short runs a day that pay gold.',
});

/** Shown in the settings footer. Replace with a build-time define when the build provides one. */
export const GAME_VERSION = '0.1.0';
