/** Player-facing text of the battle (home) tab. Registered at import time. */
import { addStrings } from '@/core/i18n';

addStrings('ko', {
  'battle.chapter': '챕터 {n}',
  'battle.best': '최고 집사 {n}단계',
  'battle.best.none': '아직 클리어 전이에요',
  'battle.chapter.locked': '앞 챕터를 먼저 클리어해요.',
  'battle.prev': '앞 챕터',
  'battle.next': '다음 챕터',
  'battle.stake': '집사 {n}단계',
  'battle.stake.add': '이 단계에서 늘어나는 규칙',
  'battle.stake.base': '기본 규칙으로 해요.',
  'battle.stake.locked': '앞 단계를 먼저 클리어해요.',
  'battle.start': '출동!',
  'battle.start.locked': '아직 잠겨 있어요',
  'battle.boss': '보스',

  'battle.patrol.title': '순찰',
  'battle.patrol.hint': '고양이들이 돌아다니며 골드를 모아 와요.',
  'battle.patrol.cap': '최대 {time}',
  'battle.patrol.collect': '받기',
  'battle.patrol.double': '2배로 받기',
  'battle.patrol.double.gain': '골드 {n}',
  'battle.patrol.empty': '조금 더 모이면 받을 수 있어요.',
  'battle.patrol.full': '가득 찼어요!',

  'battle.chest.title': '무료 상자',
  'battle.chest.ready': '열 수 있어요!',
  'battle.chest.wait': '다음 상자까지 {time}',
  'battle.chest.open': '열기',
  'battle.chest.skip.ad': '광고 보고 열기',
  'battle.chest.skip.gems': '보석으로 열기',
  'battle.chest.odds': '확률 보기',

  'battle.treat.title': '오늘의 간식',
  'battle.treat.hint': '광고를 보면 간식을 받아요.',
  'battle.treat.watch': '광고',
  'battle.treat.got': '받았어요',

  'battle.daily.title': '일일 도전',
  'battle.daily.code': '오늘의 코드',
  'battle.daily.best': '오늘 최고 {n}웨이브',
  'battle.daily.none': '오늘은 아직 도전 전이에요',
  'battle.daily.cleared': '오늘 클리어!',
  'battle.daily.play': '도전',
  'battle.daily.cup': '이번 주 컵 {score}점',
  'battle.daily.cup.next': '다음 상 {need}점',
  'battle.daily.cup.done': '모든 상을 받을 수 있어요!',
  'battle.cup.claim': '컵 상 받기',

  'battle.endless.title': '끝없는 모드',
  'battle.endless.best': '최고 {n}웨이브',
  'battle.endless.week': '이번 주 {n}웨이브',
  'battle.endless.play': '도전',
  'battle.endless.claim': '주간 상 받기',

  'battle.sweep.title': '소탕',
  'battle.sweep.tickets': '소탕권 {n}장',
  'battle.sweep.target': '{chapter} · 집사 {n}단계',
  'battle.sweep.go': '소탕하기',
  'battle.sweep.done': '소탕 완료! 경험치 +{xp}',
  'battle.sweep.need': '클리어한 단계만 소탕해요.',
  'battle.sweep.ad': '광고로 +1장',
  'battle.sweep.buy': '+1장',

  'battle.calendar': '출석',
  'battle.promo.tag': '첫 구매 한정',
  'battle.promo.buy': '{price}',
  'battle.promo.bought': '구매해 주셔서 고마워요!',
  'battle.locked': '잠김',
});

addStrings('en', {
  'battle.chapter': 'Chapter {n}',
  'battle.best': 'Best: Butler {n}',
  'battle.best.none': 'Not cleared yet',
  'battle.chapter.locked': 'Clear the chapter before it first.',
  'battle.prev': 'Previous chapter',
  'battle.next': 'Next chapter',
  'battle.stake': 'Butler {n}',
  'battle.stake.add': 'Rule added at this level',
  'battle.stake.base': 'Normal rules.',
  'battle.stake.locked': 'Clear the level before it first.',
  'battle.start': 'Go!',
  'battle.start.locked': 'Still locked',
  'battle.boss': 'Boss',

  'battle.patrol.title': 'Patrol',
  'battle.patrol.hint': 'The cats wander around and bring back gold.',
  'battle.patrol.cap': 'Up to {time}',
  'battle.patrol.collect': 'Collect',
  'battle.patrol.double': 'Collect x2',
  'battle.patrol.double.gain': 'Gold {n}',
  'battle.patrol.empty': 'Wait a little for more.',
  'battle.patrol.full': 'All full!',

  'battle.chest.title': 'Free chest',
  'battle.chest.ready': 'Ready to open!',
  'battle.chest.wait': 'Next chest in {time}',
  'battle.chest.open': 'Open',
  'battle.chest.skip.ad': 'Watch ad to open',
  'battle.chest.skip.gems': 'Open with gems',
  'battle.chest.odds': 'See odds',

  'battle.treat.title': "Today's treats",
  'battle.treat.hint': 'Watch an ad to get a treat.',
  'battle.treat.watch': 'Ad',
  'battle.treat.got': 'Got it',

  'battle.daily.title': 'Daily Challenge',
  'battle.daily.code': "Today's code",
  'battle.daily.best': 'Best today: wave {n}',
  'battle.daily.none': 'Not tried today',
  'battle.daily.cleared': 'Cleared today!',
  'battle.daily.play': 'Play',
  'battle.daily.cup': 'Weekly cup: {score} pts',
  'battle.daily.cup.next': 'Next prize at {need} pts',
  'battle.daily.cup.done': 'Every prize is yours to take!',
  'battle.cup.claim': 'Claim cup prize',

  'battle.endless.title': 'Endless Mode',
  'battle.endless.best': 'Best: wave {n}',
  'battle.endless.week': 'This week: wave {n}',
  'battle.endless.play': 'Play',
  'battle.endless.claim': 'Claim weekly prize',

  'battle.sweep.title': 'Sweep',
  'battle.sweep.tickets': '{n} tickets',
  'battle.sweep.target': '{chapter} · Butler {n}',
  'battle.sweep.go': 'Sweep',
  'battle.sweep.done': 'Swept! XP +{xp}',
  'battle.sweep.need': 'Only cleared levels can be swept.',
  'battle.sweep.ad': 'Ad: +1 ticket',
  'battle.sweep.buy': '+1 ticket',

  'battle.calendar': 'Check-in',
  'battle.promo.tag': 'First purchase',
  'battle.promo.buy': '{price}',
  'battle.promo.bought': 'Thank you for your support!',
  'battle.locked': 'Locked',
});
