/** Player-facing text of the home shell and the run flow (pre-run screen, continue prompt). Registered at import time. */
import { addStrings } from '@/core/i18n';

addStrings('ko', {
  'shell.tab.shop': '상점',
  'shell.tab.cats': '고양이',
  'shell.tab.battle': '출동',
  'shell.tab.missions': '미션',
  'shell.tab.pass': '패스',
  'shell.lv': 'Lv',
  'shell.xp': '{a} / {b}',
  'shell.logo': '냥이 수비대',
  'shell.logo.ready': '준비됐어요',

  'shell.pre.title': '출동 준비',
  'shell.pre.chapter': '챕터 {n}',
  'shell.pre.mode.daily': '일일 도전',
  'shell.pre.mode.endless': '끝없는 모드',
  'shell.pre.mode.gold': '골드 던전',
  'shell.pre.mode.chapter': '챕터',
  'shell.pre.stake': '집사 {n}단계',
  'shell.pre.rules': '이번 판 규칙',
  'shell.pre.rules.none': '기본 규칙이에요.',
  'shell.pre.daily.rules': '오늘의 규칙',
  'shell.pre.endless.rules': '끝없이 밀려와요. 얼마나 버티는지 겨뤄 보세요.',
  'shell.pre.gold.rules.waves': '{n}웨이브를 버티면 끝나요. 보스는 없고, 한 웨이브는 {s}초예요.',
  'shell.pre.gold.rules.pay': '넘긴 웨이브와 처치한 적의 수만큼 골드를 받아요. 뒤로 갈수록 더 많이 줘요.',
  'shell.pre.gold.rules.win': '끝까지 막으면 골드가 {x}배예요.',
  'shell.pre.gold.rules.first': '오늘 첫 클리어는 골드 {n}을 더 줘요.',
  'shell.pre.boss': '이 챕터의 보스',
  'shell.pre.lines': '합성 줄',
  'shell.pre.lines.hint': '같은 고양이 둘을 합치면 같은 줄의 다음 등급이 돼요.',
  'shell.pre.lines.awaken': '각성',
  'shell.pre.snack': '출발 간식',
  'shell.pre.snack.hint': '하나만 고를 수 있어요. 고르면 바로 출발해요.',
  'shell.pre.snack.fish': '생선 {n}마리',
  'shell.pre.snack.fish.desc': '시작할 때 생선을 더 받아요.',
  'shell.pre.snack.purr': '골골 {n}',
  'shell.pre.snack.purr.desc': '시작할 때 골골을 더 받아요.',
  'shell.pre.snack.rare_summon': '든든한 첫 소환',
  'shell.pre.snack.rare_summon.desc': '첫 소환이 {rarity} 이상이에요.',
  'shell.pre.ad': '광고 보기',
  'shell.pre.ad.none': '광고 없음',
  'shell.pre.start': '간식 없이 출발',
  'shell.pre.go': '출발!',

  'shell.cont.title': '이어서 할까요?',
  'shell.cont.body': '끝내지 못한 판이 있어요. 이어서 할 수 있어요.',
  'shell.cont.wave': '{n}웨이브부터',
  'shell.cont.yes': '이어서',
  'shell.cont.no': '그만두기',
  'shell.cont.giveup.title': '정말 그만둘까요?',
  'shell.cont.giveup.body': '여기까지의 보상만 받고 판을 끝내요.',
  'shell.cont.giveup.yes': '그만둘래요',
  'shell.cont.giveup.no': '이어서 할래요',
  'shell.cont.settled': '판을 정리했어요.',

  'shell.boot.warn.platform': '광고와 결제를 불러오지 못했어요. 게임은 그대로 즐길 수 있어요.',
  'shell.boot.warn.meta': '저장된 데이터를 불러오지 못했어요. 새로 시작해요.',
});

addStrings('en', {
  'shell.tab.shop': 'Shop',
  'shell.tab.cats': 'Cats',
  'shell.tab.battle': 'Battle',
  'shell.tab.missions': 'Missions',
  'shell.tab.pass': 'Pass',
  'shell.lv': 'Lv',
  'shell.xp': '{a} / {b}',
  'shell.logo': 'Meow Guard',
  'shell.logo.ready': 'Ready',

  'shell.pre.title': 'Get ready',
  'shell.pre.chapter': 'Chapter {n}',
  'shell.pre.mode.daily': 'Daily Challenge',
  'shell.pre.mode.endless': 'Endless Mode',
  'shell.pre.mode.gold': 'Gold Dungeon',
  'shell.pre.mode.chapter': 'Chapter',
  'shell.pre.stake': 'Butler {n}',
  'shell.pre.rules': 'Rules this run',
  'shell.pre.rules.none': 'Normal rules.',
  'shell.pre.daily.rules': "Today's rule",
  'shell.pre.endless.rules': 'They never stop. See how long you last.',
  'shell.pre.gold.rules.waves': 'Hold out for {n} waves. There is no boss, and a wave lasts {s} seconds.',
  'shell.pre.gold.rules.pay': 'You get gold for every wave you get through and every enemy you stop. Later waves pay more.',
  'shell.pre.gold.rules.win': 'Hold out to the end and the gold is x{x}.',
  'shell.pre.gold.rules.first': "Today's first clear pays {n} more gold.",
  'shell.pre.boss': 'Chapter boss',
  'shell.pre.lines': 'Merge lines',
  'shell.pre.lines.hint': 'Two identical cats merge into the next rank of the same line.',
  'shell.pre.lines.awaken': 'Awaken',
  'shell.pre.snack': 'Starter snack',
  'shell.pre.snack.hint': 'Pick one. The run starts right away.',
  'shell.pre.snack.fish': '{n} fish',
  'shell.pre.snack.fish.desc': 'Start with extra fish.',
  'shell.pre.snack.purr': '{n} purr',
  'shell.pre.snack.purr.desc': 'Start with extra purr.',
  'shell.pre.snack.rare_summon': 'Strong first summon',
  'shell.pre.snack.rare_summon.desc': 'Your first summon is {rarity} or better.',
  'shell.pre.ad': 'Watch ad',
  'shell.pre.ad.none': 'No ad now',
  'shell.pre.start': 'Start without snack',
  'shell.pre.go': 'Go!',

  'shell.cont.title': 'Continue?',
  'shell.cont.body': 'A run was left unfinished. You can pick it up.',
  'shell.cont.wave': 'From wave {n}',
  'shell.cont.yes': 'Continue',
  'shell.cont.no': 'Give up',
  'shell.cont.giveup.title': 'Give up this run?',
  'shell.cont.giveup.body': 'You keep the rewards earned so far and the run ends.',
  'shell.cont.giveup.yes': 'Give up',
  'shell.cont.giveup.no': 'Keep playing',
  'shell.cont.settled': 'The run was wrapped up.',

  'shell.boot.warn.platform': "Ads and purchases couldn't load. You can still play.",
  'shell.boot.warn.meta': "Saved data couldn't be loaded. Starting fresh.",
});
