/** Every player-facing line of the battle HUD, Korean (primary, 해요체) and English. Keys: hud.* */
import { addStrings } from '@/core/i18n';

addStrings('ko', {
  // top area
  'hud.wave': '{act}막 · 웨이브 {wave}/{total}',
  'hud.waveOpen': '{act}막 · 웨이브 {wave}',
  'hud.prep': '준비해요',
  'hud.ready': '소환해요',
  'hud.secs': '{s}초',
  'hud.gauge': '{n} / {cap}',
  'hud.overflow': '넘쳤어요! {s}초',
  'hud.est': '예상 {s}초',
  'hud.est.wait': '계산 중',
  'hud.est.none': '예상 불가',
  'hud.est.far': '예상 99초 이상',

  // bottom panel
  'hud.summon': '소환',
  'hud.free': '무료',
  'hud.full': '자리 없음',
  'hud.fullHint': '합치거나 팔아요',
  'hud.short': '{n} 부족',
  'hud.tracker': '3택',
  'hud.call': '다음 웨이브',
  'hud.max': '최고',
  'hud.maxed': '최고 단계',
  'hud.upgrade': '강화',
  'hud.ad': '광고',
  'hud.cancel': '취소',
  'hud.recommend': '추천',

  // class sheet
  'hud.class.have': '서로 다른 고양이 {n}종',
  'hud.class.need': '{n}종',
  'hud.class.need.more': '{n}종 이상',
  'hud.class.level': '직업 강화 {lv}/{max}',
  'hud.class.note': '단계마다 이 직업의 피해가 {n}%씩 늘어요.',
  'hud.class.rule': '같은 고양이 둘을 합치면 같은 직업의 다음 등급이 돼요.',
  'hud.class.goal': '시너지 {tier}단계까지 {n}종 더',
  'hud.class.goalMax': '시너지 최고 단계예요',
  'hud.ladder.merge': '합성',
  'hud.ladder.awaken': '각성',

  // what a cat becomes (selection sheet)
  'hud.plan.merge': '합치면',
  'hud.plan.awaken': '각성하면',
  'hud.plan.top': '가장 높은 등급이에요',
  'hud.plan.have': '같은 고양이 {n}마리',
  'hud.plan.rule': '{n}마리부터 합쳐요',
  'hud.plan.ready': '끌어서 합쳐요!',
  'hud.plan.synergy': '시너지 {now}/{need}단계',
  'hud.plan.purr': '골골 {have}/{need}',

  // odds
  'hud.odds.title': '소환 확률',
  'hud.odds.grade': '소환 등급 {lv}단계',
  'hud.odds.status': '천장: 골목대장 이상 안 나온 횟수 {n}/{limit} · 추가 확률 +{bonus}%p',
  'hud.pity': '천장',
  'hud.odds.rule': '골목대장 이상이 {limit}번 안 나오면 {next}번째부터 소환마다 확률이 쌓여요. 나오면 처음부터 다시 세요. 위 표는 다음 소환에 실제로 쓰는 확률이에요.',
  'hud.odds.tutorial': '처음 세 번의 소환은 튜토리얼 대본이에요. 그 뒤부터는 위 표대로 나와요.',

  // selection sheet
  'hud.molt': '털갈이',
  'hud.molt.sub': '{cost} · 남은 {left}번',
  'hud.molt.info': '골골 {cost}개로 같은 등급의 다른 직업이 돼요. 남은 털갈이 {left}번',
  'hud.awaken': '각성',
  'hud.awaken.r.legend': '대왕만 가능',
  'hud.awaken.r.synergy': '시너지 2단계',
  'hud.awaken.r.purr': '골골 {n} 필요',
  'hud.awaken.r.other': '지금은 안 돼요',
  'hud.sell': '판매',
  'hud.sell.both': '+{fish} · 골골 +{purr}',
  'hud.sell.drag': '여기에 놓으면 판매 {gain}',
  'hud.sell.drop': '놓으면 판매 {gain}',
  'hud.stat.interval': '{s}초',

  // pick of three
  'hud.pick.title': '하나를 골라요',
  'hud.pick.sub': '이번 소환은 세 마리 중에서 골라요.',
  'hud.pick.tip': '꾹 누르면 능력이 보여요',

  // toy choice
  'hud.relic.title': '장난감 고르기',
  'hud.relic.cleared': '{act}막 클리어!',
  'hud.relic.one': '장난감을 하나 골라요.',
  'hud.relic.many': '장난감을 {n}개 더 고를 수 있어요.',
  'hud.relic.reroll': '다시 뽑기',
  'hud.relic.free': '무료 {n}번',
  'hud.relic.test': '테스트',
  'hud.relic.noMore': '다시 뽑기는 이미 썼어요.',

  // pause and settings
  'hud.pause.title': '일시정지',
  'hud.pause.resume': '계속하기',
  'hud.pause.restart': '다시 시작',
  'hud.pause.restartAsk': '지금 판은 사라지고 처음부터 시작해요. 괜찮아요?',
  'hud.pause.quit': '나가기',
  'hud.pause.quitAsk': '지금 판을 끝내고 결과를 봐요. 괜찮아요?',
  'hud.settings': '설정',
  'hud.set.sfx': '효과음',
  'hud.set.music': '음악',
  'hud.set.shake': '화면 흔들림',
  'hud.set.shake.full': '보통',
  'hud.set.shake.reduced': '줄임',
  'hud.set.shake.off': '끔',
  'hud.set.flashes': '번쩍임',
  'hud.set.reduceMotion': '움직임 줄이기',
  'hud.set.haptics': '진동',
  'hud.set.numbers': '피해 숫자',
  'hud.set.numbers.full': '전체',
  'hud.set.numbers.brief': '간략',
  'hud.set.numbers.off': '끔',
  'hud.set.lang': '언어',

  // continue
  'hud.cont.title': '계속할까요?',
  'hud.cont.where': '웨이브 {n}/{total}까지 왔어요',
  'hud.cont.why.over': '적이 너무 많아져서 졌어요.',
  'hud.cont.why.boss': '제한 시간 안에 못 잡았어요.',
  'hud.cont.fix.over': '계속하면 적이 크게 줄고 4초를 더 줘요.',
  'hud.cont.fix.boss': '계속하면 보스 체력이 35% 줄고 시간이 20초 늘어요.',
  'hud.cont.ad': '광고 보고 계속하기',
  'hud.cont.gems': '보석으로 계속하기',
  'hud.cont.go': '계속하기',
  'hud.cont.quit': '그만할래요',

  // result
  'hud.res.title': '결과',
  'hud.res.win': '승리!',
  'hud.res.lose': '아쉬워요',
  'hud.res.winSub': '냥이 수비대가 집을 지켰어요!',
  'hud.res.loseSub': '다음엔 더 잘할 수 있어요.',
  'hud.res.close': '{n}웨이브만 더 가면 클리어였어요!',
  'hud.res.loseFish': '물고기가 {n}마리 남았어요. 고양이를 더 불러요!',
  'hud.res.waves': '웨이브',
  'hud.res.kills': '처치',
  'hud.res.merges': '합성',
  'hud.res.best': '최고 등급',
  'hud.res.time': '플레이 시간',
  'hud.res.summons': '소환',
  'hud.res.luck.top': '이번 판 소환 운: 상위 {n}%',
  'hud.res.luck.low': '이번 판 소환 운이 하위 {n}%였어요. 실력 탓이 아니에요!',
  'hud.res.luck.avg': '이번 판 소환 운은 평균이었어요.',
  'hud.res.seed': '시드 {seed}',
  'hud.res.rewards': '보상',
  'hud.res.level': '계정 레벨 {a} → {b}!',
  'hud.res.firstClear': '새 단계 클리어! 챕터 {chapter} · 집사 {stake}단계',
  'hud.res.newBest': '최고 기록!',
  'hud.res.r.gold': '골드',
  'hud.res.r.xp': '경험치',
  'hud.res.r.gems': '보석',
  'hud.res.r.tickets': '소탕권',
  'hud.res.r.cosmetic': '꾸미기',
  'hud.res.chest.wooden': '나무 상자',
  'hud.res.chest.silver': '은 상자',
  'hud.res.chest.gold': '금 상자',
  'hud.res.double': '보상 2배로 받기',
  'hud.res.doubled': '2배로 받았어요',
  'hud.res.butler': '집사 패스',
  'hud.res.snack': '간식 상자 받기',
  'hud.res.snackLeft': '오늘 {n}번 남음',
  'hud.res.snackDone': '상자를 받았어요',
  'hud.res.home': '홈',
  'hud.res.retry': '다시 도전',

  // tutorial
  'hud.tut.summon': '버튼을 눌러 고양이를 불러요! ({n}/{total})',
  'hud.tut.merge': '같은 고양이끼리 끌어서 합쳐요! 같은 직업의 다음 등급이 돼요.',
  'hud.tut.more': '물고기가 넉넉해요! 고양이를 더 불러요!',

  // laser
  'hud.laser.hint': '길 위를 눌러 빨간 점을 찍어요. 점 가까이 있는 적부터 공격해요.',
  'hud.laser.coolLeft': '충전 중이에요. {s}초 뒤에 다시 쓸 수 있어요.',
  'hud.laserCard.title': '레이저 포인터',
  'hud.laserCard.row1': '길 위에 점을 찍으면 {dur}초 동안 고양이들이 점에서 가장 가까운 적부터 공격해요.',
  'hud.laserCard.row2': '점 근처의 표시된 적은 받는 피해가 +{pct}% 늘어요.',
  'hud.laserCard.row3': '다 쓰면 {cd}초 뒤에 다시 쓸 수 있어요.',
  'hud.laserCard.mods': '더 좋아지려면',
  'hud.laserCard.toyHave': '장난감 {name} (지금 있어요)',
  'hud.laserCard.toyNone': '장난감 {name} (아직 없어요)',
  'hud.laserCard.toyFx': '지속 +{dur}초 · 충전 −{cut}초',
  'hud.laserCard.train': '훈련 {name} (지금 {n}단계)',
  'hud.laserCard.trainFx': '단계마다 충전 −{cut}초 · 지금 −{now}초',
  'hud.laserCard.rule': '오늘의 규칙: 충전이 {cd}초예요.',
  'hud.laserCard.use': '써 볼게요',
  'hud.laserCard.got': '알겠어요',
  'hud.laserGuide.press': '레이저 포인터가 생겼어요! 눌러서 알아봐요.',
  'hud.laserGuide.place': '길 위를 눌러 빨간 점을 찍어요. 끌면 점이 따라와요.',
  'hud.laserGuide.see': '점 근처 적에게 표시가 붙었어요. 고양이들이 그 적부터 공격해요!',
  'hud.laserGuide.done': '잘했어요! 적이 몰릴 때 써 봐요.',
  'hud.laser.active': '지금 레이저가 켜져 있어요. 점을 끌어서 옮겨요.',

  // refused commands
  'hud.fail.not_enough_fish': '생선이 모자라요.',
  'hud.fail.not_enough_purr': '골골이 모자라요. 막을 깰 때 받아요.',
  'hud.fail.board_full': '자리가 없어요. 고양이를 합치거나 팔아 보세요.',
  'hud.fail.choice_pending': '먼저 고르는 중이에요.',
  'hud.fail.not_in_battle': '지금은 쓸 수 없어요.',
  'hud.fail.invalid_cell': '그 칸에는 놓을 수 없어요.',
  'hud.fail.empty_cell': '빈 칸이에요.',
  'hud.fail.max_level': '이미 가장 높은 단계예요.',
  'hud.fail.not_legendary': '대왕만 수호신이 될 수 있어요.',
  'hud.fail.synergy_too_low': '같은 직업 시너지 2단계가 필요해요.',
  'hud.fail.molt_limit': '이번 판 털갈이를 모두 썼어요.',
  'hud.fail.on_cooldown': '아직 다시 쓸 수 없어요.',
  'hud.fail.not_available': '지금은 쓸 수 없어요.',
  'hud.fail.already_used': '이번 판에 이미 썼어요.',
  'hud.fail.nothing_to_do': '바뀌는 게 없어요.',
  'hud.fail.callNextWave.not_available': '적이 다 나온 뒤에 부를 수 있어요.',
  'hud.fail.upgradeSummon.max_level': '소환 등급이 이미 가장 높아요.',
  'hud.fail.upgradeClass.max_level': '이 직업은 이미 가장 높은 단계예요.',
  'hud.fail.upgradeSummon.not_enough_fish': '생선이 모자라요. 등급을 올리려면 생선이 더 필요해요.',
  'hud.fail.upgradeClass.not_enough_fish': '생선이 모자라요. 직업을 강화하려면 생선이 더 필요해요.',
  'hud.fail.molt.not_enough_purr': '골골이 모자라요. 털갈이에는 골골이 필요해요.',
  'hud.fail.awaken.not_enough_purr': '골골이 모자라요. 각성에는 골골이 필요해요.',
  'hud.fail.awaken.empty_cell': '각성할 고양이를 먼저 골라요.',
  'hud.fail.rerollRelics.already_used': '다시 뽑기는 이미 썼어요.',
  'hud.fail.setLaser.on_cooldown': '레이저를 충전하고 있어요.',
  'hud.fail.laser.on_cooldown': '레이저를 충전하고 있어요.',
  'hud.fail.drop.invalid_cell': '그 칸에는 놓을 수 없어요.',

  // first-time speech bubbles
  'hud.hint.chips': '직업 칩이에요. 눌러서 자세히 봐요.',
  'hud.hint.synergy': '시너지가 켜졌어요! 같은 직업 종류가 많을수록 강해져요.',
  'hud.hint.toys': '장난감이 생겼어요. 눌러서 효과를 확인해요.',
  'hud.hint.sun': '햇살 칸이 새 자리로 옮겨 갔어요. 거기 선 고양이는 더 빨라요!',
  'hud.hint.speed': '누를 때마다 배속이 바뀌어요.',
  'hud.hint.preview': '다음 웨이브에 나올 적이에요. 눌러서 알아봐요.',
  'hud.hint.tracker': '6번째 소환마다 세 마리 중 하나를 골라요.',
  'hud.hint.laser': '레이저예요. 길 위를 눌러 빨간 점을 찍어요.',
  'hud.hint.callWave': '미리 불러서 생선 보너스를 받아요!',
  'hud.hint.purr': '골골이에요. 털갈이와 각성에 써요.',
  'hud.hint.molt': '골골로 같은 등급의 다른 직업으로 바꿔요.',
  'hud.hint.odds': '눌러서 다음 소환의 진짜 확률을 봐요.',
  'hud.hint.grade': '소환 등급을 올리면 좋은 고양이가 더 잘 나와요.',
  'hud.hint.awaken': '대왕은 시너지 2단계에서 골골을 모으면 수호신이 돼요.',
  'hud.hint.sell': '팔면 생선을 돌려받아요. 고양이를 아래로 끌어다 놓아도 돼요.',
  'hud.hint.twins': '같은 고양이 둘을 합치면 같은 직업의 다음 등급이 돼요.',
});

addStrings('en', {
  'hud.wave': 'Act {act} · Wave {wave}/{total}',
  'hud.waveOpen': 'Act {act} · Wave {wave}',
  'hud.prep': 'Get ready',
  'hud.ready': 'Summon!',
  'hud.secs': '{s}s',
  'hud.gauge': '{n} / {cap}',
  'hud.overflow': 'Overrun! {s}s',
  'hud.est': 'Est. {s}s',
  'hud.est.wait': 'Estimating',
  'hud.est.none': 'No damage',
  'hud.est.far': 'Est. 99s+',

  'hud.summon': 'Summon',
  'hud.free': 'Free',
  'hud.full': 'No space',
  'hud.fullHint': 'Merge or sell',
  'hud.short': '{n} short',
  'hud.tracker': 'Pick 3',
  'hud.call': 'Next wave',
  'hud.max': 'MAX',
  'hud.maxed': 'Max level',
  'hud.upgrade': 'Upgrade',
  'hud.ad': 'Watch ad',
  'hud.cancel': 'Cancel',
  'hud.recommend': 'Best',

  'hud.class.have': 'Different cats: {n}',
  'hud.class.need': '{n} kinds',
  'hud.class.need.more': '{n}+ kinds',
  'hud.class.level': 'Class upgrade {lv}/{max}',
  'hud.class.note': 'Each level adds {n}% damage to this class.',
  'hud.class.rule': 'Merging two identical cats makes the next rank of the same class.',
  'hud.class.goal': '{n} more for tier {tier}',
  'hud.class.goalMax': 'Top synergy tier',
  'hud.ladder.merge': 'Merge',
  'hud.ladder.awaken': 'Awaken',

  'hud.plan.merge': 'Merge',
  'hud.plan.awaken': 'Awaken',
  'hud.plan.top': 'Highest rank',
  'hud.plan.have': 'Same cat: {n}',
  'hud.plan.rule': 'Need {n} to merge',
  'hud.plan.ready': 'Drag to merge!',
  'hud.plan.synergy': 'Synergy {now}/{need}',
  'hud.plan.purr': 'Purr {have}/{need}',

  'hud.odds.title': 'Summon odds',
  'hud.odds.grade': 'Summon grade {lv}',
  'hud.odds.status': 'Pity: summons without Alley Boss+: {n}/{limit} · bonus +{bonus} pts',
  'hud.pity': 'Pity',
  'hud.odds.rule': 'If {limit} summons in a row give no Alley Boss or better, every summon from the {next}th adds to the chance until one shows up. The table above is exactly what the next summon rolls on.',
  'hud.odds.tutorial': 'The first three summons are scripted for the tutorial. After that, the table above is what you get.',

  'hud.molt': 'Molt',
  'hud.molt.sub': '{cost} · {left} left',
  'hud.molt.info': 'Spend {cost} purr to become another class of the same rarity. Molts left: {left}',
  'hud.awaken': 'Awaken',
  'hud.awaken.r.legend': 'Kings only',
  'hud.awaken.r.synergy': 'Needs tier 2',
  'hud.awaken.r.purr': 'Needs {n} purr',
  'hud.awaken.r.other': 'Not now',
  'hud.sell': 'Sell',
  'hud.sell.both': '+{fish} · purr +{purr}',
  'hud.sell.drag': 'Drop here to sell {gain}',
  'hud.sell.drop': 'Release to sell {gain}',
  'hud.stat.interval': '{s}s',

  'hud.pick.title': 'Pick one',
  'hud.pick.sub': 'This summon: choose one of three cats.',
  'hud.pick.tip': 'Hold a card to see its skill',

  'hud.relic.title': 'Pick a toy',
  'hud.relic.cleared': 'Act {act} cleared!',
  'hud.relic.one': 'Choose one toy.',
  'hud.relic.many': 'You can choose {n} more toys.',
  'hud.relic.reroll': 'Reroll',
  'hud.relic.free': '{n} free',
  'hud.relic.test': 'Test',
  'hud.relic.noMore': 'You already used the reroll.',

  'hud.pause.title': 'Paused',
  'hud.pause.resume': 'Resume',
  'hud.pause.restart': 'Restart',
  'hud.pause.restartAsk': 'This run will be lost and a new one starts. Sure?',
  'hud.pause.quit': 'Quit',
  'hud.pause.quitAsk': 'End this run now and see the result. Sure?',
  'hud.settings': 'Settings',
  'hud.set.sfx': 'Sound effects',
  'hud.set.music': 'Music',
  'hud.set.shake': 'Screen shake',
  'hud.set.shake.full': 'Full',
  'hud.set.shake.reduced': 'Reduced',
  'hud.set.shake.off': 'Off',
  'hud.set.flashes': 'Flashes',
  'hud.set.reduceMotion': 'Reduce motion',
  'hud.set.haptics': 'Vibration',
  'hud.set.numbers': 'Damage numbers',
  'hud.set.numbers.full': 'All',
  'hud.set.numbers.brief': 'Brief',
  'hud.set.numbers.off': 'Off',
  'hud.set.lang': 'Language',

  'hud.cont.title': 'Continue?',
  'hud.cont.where': 'You reached wave {n}/{total}',
  'hud.cont.why.over': 'Too many enemies got through.',
  'hud.cont.why.boss': 'The boss was not beaten in time.',
  'hud.cont.fix.over': 'Continue to clear most enemies and get 4 more seconds.',
  'hud.cont.fix.boss': 'Continue for 35% less boss health and 20 more seconds.',
  'hud.cont.ad': 'Watch an ad to continue',
  'hud.cont.gems': 'Continue with gems',
  'hud.cont.go': 'Continue',
  'hud.cont.quit': 'No thanks',

  'hud.res.title': 'Result',
  'hud.res.win': 'Victory!',
  'hud.res.lose': 'Defeated',
  'hud.res.winSub': 'The Meow Guard saved the house!',
  'hud.res.loseSub': 'You will do better next time.',
  'hud.res.close': 'Only {n} more waves to clear it!',
  'hud.res.loseFish': 'You had {n} fish left. Spend them on cats!',
  'hud.res.waves': 'Waves',
  'hud.res.kills': 'Kills',
  'hud.res.merges': 'Merges',
  'hud.res.best': 'Best rarity',
  'hud.res.time': 'Time',
  'hud.res.summons': 'Summons',
  'hud.res.luck.top': 'Summon luck this run: top {n}%',
  'hud.res.luck.low': 'Summon luck was in the bottom {n}% this run. Not your fault!',
  'hud.res.luck.avg': 'Summon luck was about average this run.',
  'hud.res.seed': 'Seed {seed}',
  'hud.res.rewards': 'Rewards',
  'hud.res.level': 'Account level {a} → {b}!',
  'hud.res.firstClear': 'New stage cleared! Chapter {chapter} · Butler {stake}',
  'hud.res.newBest': 'New best!',
  'hud.res.r.gold': 'Gold',
  'hud.res.r.xp': 'XP',
  'hud.res.r.gems': 'Gems',
  'hud.res.r.tickets': 'Tickets',
  'hud.res.r.cosmetic': 'Cosmetic',
  'hud.res.chest.wooden': 'Wooden chest',
  'hud.res.chest.silver': 'Silver chest',
  'hud.res.chest.gold': 'Gold chest',
  'hud.res.double': 'Double the rewards',
  'hud.res.doubled': 'Doubled',
  'hud.res.butler': 'Butler Pass',
  'hud.res.snack': 'Get a snack box',
  'hud.res.snackLeft': '{n} left today',
  'hud.res.snackDone': 'Box received',
  'hud.res.home': 'Home',
  'hud.res.retry': 'Try again',

  'hud.tut.summon': 'Tap to summon a cat! ({n}/{total})',
  'hud.tut.merge': 'Drag one cat onto its twin to merge! You get the next rank of the same class.',
  'hud.tut.more': 'Fish ready! Summon more cats!',

  'hud.laser.hint': 'Tap the walkway to place the red dot. Cats hit enemies near it first.',
  'hud.laser.coolLeft': 'Recharging. Ready again in {s}s.',
  'hud.laserCard.title': 'Laser Pointer',
  'hud.laserCard.row1': 'Place the dot on the walkway: for {dur}s your cats attack the enemy closest to it first.',
  'hud.laserCard.row2': 'Marked enemies near the dot take +{pct}% damage.',
  'hud.laserCard.row3': 'Ready again {cd}s after it ends.',
  'hud.laserCard.mods': 'What makes it better',
  'hud.laserCard.toyHave': 'Toy {name} (you have it)',
  'hud.laserCard.toyNone': 'Toy {name} (not yet)',
  'hud.laserCard.toyFx': 'Lasts +{dur}s · recharges {cut}s sooner',
  'hud.laserCard.train': 'Training {name} (level {n})',
  'hud.laserCard.trainFx': 'Recharge -{cut}s per level · now -{now}s',
  'hud.laserCard.rule': "Today's rule: recharge is {cd}s.",
  'hud.laserCard.use': 'Use it',
  'hud.laserCard.got': 'Got it',
  'hud.laserGuide.press': 'You got the laser pointer! Tap it to see what it does.',
  'hud.laserGuide.place': 'Tap the walkway to drop the red dot. Drag to move it.',
  'hud.laserGuide.see': 'Enemies near the dot are marked. Your cats attack them first!',
  'hud.laserGuide.done': 'Nice! Use it when enemies bunch up.',
  'hud.laser.active': 'The laser is on. Drag the dot to move it.',

  'hud.fail.not_enough_fish': 'Not enough fish.',
  'hud.fail.not_enough_purr': 'Not enough purr. You get it when you clear an act.',
  'hud.fail.board_full': 'No space left. Merge or sell a cat.',
  'hud.fail.choice_pending': 'Finish your choice first.',
  'hud.fail.not_in_battle': 'Not possible right now.',
  'hud.fail.invalid_cell': 'You cannot drop it there.',
  'hud.fail.empty_cell': 'That cell is empty.',
  'hud.fail.max_level': 'Already at the highest level.',
  'hud.fail.not_legendary': 'Only Kings can become Guardians.',
  'hud.fail.synergy_too_low': 'You need class synergy tier 2.',
  'hud.fail.molt_limit': 'No molts left this run.',
  'hud.fail.on_cooldown': 'Not ready yet.',
  'hud.fail.not_available': 'Not possible right now.',
  'hud.fail.already_used': 'Already used this run.',
  'hud.fail.nothing_to_do': 'Nothing would change.',
  'hud.fail.callNextWave.not_available': 'You can call it once every enemy has spawned.',
  'hud.fail.upgradeSummon.max_level': 'Summon grade is already max.',
  'hud.fail.upgradeClass.max_level': 'This class is already at max level.',
  'hud.fail.upgradeSummon.not_enough_fish': 'Not enough fish to raise the summon grade.',
  'hud.fail.upgradeClass.not_enough_fish': 'Not enough fish to upgrade this class.',
  'hud.fail.molt.not_enough_purr': 'Not enough purr to molt.',
  'hud.fail.awaken.not_enough_purr': 'Not enough purr to awaken.',
  'hud.fail.awaken.empty_cell': 'Pick a cat to awaken first.',
  'hud.fail.rerollRelics.already_used': 'You already used the reroll.',
  'hud.fail.setLaser.on_cooldown': 'The laser is recharging.',
  'hud.fail.laser.on_cooldown': 'The laser is recharging.',
  'hud.fail.drop.invalid_cell': 'You cannot drop it there.',

  'hud.hint.chips': 'Class chips. Tap one for details.',
  'hud.hint.synergy': 'Synergy is on! More kinds of cats, higher tier.',
  'hud.hint.toys': 'You got a toy. Tap it to see what it does.',
  'hud.hint.sun': 'The sunny cells moved! Cats standing there attack faster.',
  'hud.hint.speed': 'Tap to change the game speed.',
  'hud.hint.preview': 'Enemies of the next wave. Tap one to learn more.',
  'hud.hint.tracker': 'Every 6th summon lets you pick one of three cats.',
  'hud.hint.laser': 'The laser. Tap the walkway to drop the red dot.',
  'hud.hint.callWave': 'Call the next wave early for bonus fish!',
  'hud.hint.purr': 'Purr pays for molting and awakening.',
  'hud.hint.molt': 'Purr turns a cat into another class of the same rank.',
  'hud.hint.odds': 'Tap to see the real odds of the next summon.',
  'hud.hint.grade': 'A higher summon grade makes better cats more likely.',
  'hud.hint.awaken': 'Kings awaken into Guardians at tier 2 with enough purr.',
  'hud.hint.sell': 'Sell for fish, or drag a cat down onto the panel.',
  'hud.hint.twins': 'Two identical cats merge into the next rank of their class.',
});
