import { addStrings } from '@/core/i18n';

addStrings('ko', {
  'shop.tab.chests': '상자',
  'shop.tab.daily': '오늘',
  'shop.tab.gems': '보석',
  'shop.tab.pass': '패스',
  'shop.tab.cosmetics': '꾸미기',
  'shop.tab.tickets': '소탕권',
  'shop.sec.chests': '상자',
  'shop.sec.daily': '오늘의 상점',
  'shop.sec.gems': '보석과 패키지',
  'shop.sec.pass': '패스',
  'shop.sec.piggy': '저금통',
  'shop.sec.cosmetics': '꾸미기',
  'shop.sec.tickets': '소탕권',

  'shop.free.title': '무료 나무 상자',
  'shop.free.ready': '지금 받을 수 있어요!',
  'shop.free.wait': '다음 상자까지 {time}',
  'shop.free.take': '무료로 열기',
  'shop.free.ad': '광고 보고 바로 열기',
  'shop.free.adLeft': '오늘 {n}번 남음',
  'shop.free.gems': '바로 열기',
  'shop.chest.open': '열기',
  'shop.chest.openN': '열기 ({n})',
  'shop.chest.openAll': '한번에 열기 ({n})',
  'shop.chest.buy': '사서 열기',
  'shop.chest.buyPack': '{n}개 사서 열기',
  'shop.chest.cards': '카드 {n}장',
  'shop.chest.odds': '확률',
  'shop.chest.pity': '연 금 상자 {n}/{every}',
  'shop.chest.pityTarget': '대상: {unit}',
  'shop.chest.pityNow': '이번 상자에 보너스 카드 {n}장!',
  'shop.chest.guarantee': '{rarity} {n}장은 꼭 나와요',
  'shop.chest.confirmTitle': '{chest}을(를) 살까요?',
  'shop.chest.confirmTitleN': '{chest} {n}개를 살까요?',
  'shop.chest.many.wooden': '나무 상자',
  'shop.chest.many.silver': '은 상자',
  'shop.chest.many.gold': '금 상자',
  'shop.chest.cardsAll': '상자 {count}개에 카드 {n}장',
  'shop.chest.cardsEach': '상자 하나는 카드 {n}장이에요. 아래 확률과 보장은 상자마다 똑같이 적용돼요.',
  'shop.chest.cardsEachBonus': '상자 하나는 카드 {n}장이고, 보너스 카드 {bonus}장이 더 들어요. 아래 확률과 보장은 상자마다 똑같이 적용돼요.',
  'shop.chest.confirmBuy': '사기',
  'shop.chest.cancel': '취소',

  'shop.daily.sub': '매일 새로 바뀌어요',
  'shop.daily.free': '무료',
  'shop.daily.bought': '구매 완료',
  'shop.daily.refresh': '새로 고침',
  'shop.daily.refreshLeft': '오늘 {n}번 남음',

  'shop.gems.sub': '한 번만 살 수 있는 패키지는 사면 사라져요.',
  'shop.gems.once': '1회 한정',
  'shop.gems.best': '인기',
  'shop.buy.cancel': '결제를 취소했어요.',
  'shop.buy.fail': '결제가 끝나지 않았어요. 돈은 빠져나가지 않았어요.',
  'shop.buy.unavailable': '지금은 결제할 수 없어요.',
  'shop.buy.thanks': '구매해 주셔서 고마워요!',

  'shop.butler.title': '집사 패스',
  'shop.butler.owned': '쓰는 중이에요',
  'shop.butler.perks': '3배속, 광고 없이 보상 2배, 상자 바로 열기, 순찰 2배',
  'shop.butler.note': '전투 안의 이득은 없어요.',
  'shop.gempass.title': '월간 보석 패스',
  'shop.gempass.desc': '지금 보석 {now}개, 30일 동안 매일 {daily}개',
  'shop.gempass.left': '{days}일 남았어요',
  'shop.gempass.claim': '오늘 {n}개 받기',
  'shop.gempass.claimed': '오늘 것은 받았어요',
  'shop.piggy.desc': '전투할 때마다 보너스 보석이 쌓여요.',
  'shop.piggy.pool': '{n} / {cap}',
  'shop.piggy.empty': '아직 비어 있어요. 한 판 하면 쌓이기 시작해요.',
  'shop.piggy.break': '깨기',
  'shop.piggy.free': '무료로 {n}개 꺼내기',

  'shop.cos.rugs': '러그',
  'shop.cos.fx': '소환 이펙트',
  'shop.cos.equip': '쓰기',
  'shop.cos.equipped': '쓰는 중',
  'shop.cos.chapter': '챕터 {n}을(를) 깨면 열려요',
  'shop.cos.reward': '패키지·이벤트 보상',

  'shop.tickets.sub': '깬 단계를 싸우지 않고 보상만 받아요.',
  'shop.tickets.have': '{n}/{stock}장',
  'shop.tickets.buy': '1장 사기',
  'shop.tickets.ad': '광고 보고 {n}장',
  'shop.tickets.adLeft': '오늘 {n}번 남음',

  'shop.need.gemsTitle': '보석이 모자라요',
  'shop.need.gems': '보석이 {n}개 더 필요해요. 보석을 보러 갈까요?',
  'shop.need.goGems': '보석 보기',
  'shop.need.goldTitle': '골드가 모자라요',
  'shop.need.gold': '골드가 {n} 모자라요. 전투에서 모아 볼까요?',
  'shop.need.goBattle': '전투하러 가기',
  'shop.need.later': '나중에',
  'shop.need.unavailable': '이 기기에서는 보석을 살 수 없어요. 전투와 미션으로 모아 보세요.',

  'rewards.title': '받은 보상',
  'rewards.claim': '받기',
  'rewards.wild': '{rarity} 만능 카드',

  'reveal.skip': '건너뛰기',
  'reveal.done': '확인',
  'reveal.wild': '만능',
  'reveal.bonus': '보너스',
  'reveal.total': '카드 {n}장',
  'reveal.chests': '상자 {n}개를 열었어요',
  'reveal.wildTotal': '그중 만능 카드 {n}장',
  'reveal.overflow': '더 못 쓰는 카드는 골드 {n}(으)로 바꿨어요.',

  'odds.title': '상자 확률',
  'odds.cards': '카드 {n}장',
  'odds.rows': '카드 한 장마다 나올 확률',
  'odds.guarantee': '보장',
  'odds.pity': '보너스 카드',
  'odds.counter': '지금까지 {n}/{every}',
  'odds.next': '이번에 여는 상자에 보너스 카드가 들어가요!',
  'odds.fair': '결제나 광고와 상관없이 확률은 모두 같아요.',
  'odds.where': '유닛은 뽑기로 팔지 않아요. 상자는 성장 속도만 바꿔요.',
});

addStrings('en', {
  'shop.tab.chests': 'Chests',
  'shop.tab.daily': 'Daily',
  'shop.tab.gems': 'Gems',
  'shop.tab.pass': 'Passes',
  'shop.tab.cosmetics': 'Style',
  'shop.tab.tickets': 'Tickets',
  'shop.sec.chests': 'Chests',
  'shop.sec.daily': "Today's shop",
  'shop.sec.gems': 'Gems and packs',
  'shop.sec.pass': 'Passes',
  'shop.sec.piggy': 'Piggy bank',
  'shop.sec.cosmetics': 'Style',
  'shop.sec.tickets': 'Sweep tickets',

  'shop.free.title': 'Free chest',
  'shop.free.ready': 'Ready to open!',
  'shop.free.wait': 'Next chest in {time}',
  'shop.free.take': 'Open for free',
  'shop.free.ad': 'Open with an ad',
  'shop.free.adLeft': '{n} left today',
  'shop.free.gems': 'Open now',
  'shop.chest.open': 'Open',
  'shop.chest.openN': 'Open ({n})',
  'shop.chest.openAll': 'Open all ({n})',
  'shop.chest.buy': 'Buy and open',
  'shop.chest.buyPack': 'Buy {n} and open',
  'shop.chest.cards': '{n} cards',
  'shop.chest.odds': 'Odds',
  'shop.chest.pity': 'Chests opened {n}/{every}',
  'shop.chest.pityTarget': 'Target: {unit}',
  'shop.chest.pityNow': 'This chest adds {n} bonus cards!',
  'shop.chest.guarantee': '{n} {rarity} guaranteed',
  'shop.chest.confirmTitle': 'Buy a {chest}?',
  'shop.chest.confirmTitleN': 'Buy {n} {chest}?',
  'shop.chest.many.wooden': 'Wooden chests',
  'shop.chest.many.silver': 'Silver chests',
  'shop.chest.many.gold': 'Gold chests',
  'shop.chest.cardsAll': '{n} cards in {count} chests',
  'shop.chest.cardsEach': 'Each chest holds {n} cards. The odds and guarantees below apply to every chest.',
  'shop.chest.cardsEachBonus': 'Each chest holds {n} cards, and {bonus} bonus cards come on top. The odds and guarantees below apply to every chest.',
  'shop.chest.confirmBuy': 'Buy',
  'shop.chest.cancel': 'Cancel',

  'shop.daily.sub': 'Changes every day',
  'shop.daily.free': 'Free',
  'shop.daily.bought': 'Bought',
  'shop.daily.refresh': 'Refresh',
  'shop.daily.refreshLeft': '{n} left today',

  'shop.gems.sub': 'One-time packs disappear once bought.',
  'shop.gems.once': 'One time',
  'shop.gems.best': 'Popular',
  'shop.buy.cancel': 'Purchase cancelled.',
  'shop.buy.fail': 'The purchase did not go through. You were not charged.',
  'shop.buy.unavailable': 'Purchases are not available right now.',
  'shop.buy.thanks': 'Thank you for your purchase!',

  'shop.butler.title': 'Butler Pass',
  'shop.butler.owned': 'Active',
  'shop.butler.perks': '3x speed, ad-free double rewards, instant chests, double patrol',
  'shop.butler.note': 'No advantage inside a run.',
  'shop.gempass.title': 'Monthly Gem Pass',
  'shop.gempass.desc': '{now} gems now, {daily} every day for 30 days',
  'shop.gempass.left': '{days} days left',
  'shop.gempass.left.one': '1 day left',
  'shop.gempass.claim': 'Claim {n} today',
  'shop.gempass.claimed': "Today's gems claimed",
  'shop.piggy.desc': 'Bonus gems pile up with every run.',
  'shop.piggy.pool': '{n} / {cap}',
  'shop.piggy.empty': 'Empty for now. Play a run and it starts to fill.',
  'shop.piggy.break': 'Break',
  'shop.piggy.free': 'Take {n} for free',

  'shop.cos.rugs': 'Rugs',
  'shop.cos.fx': 'Summon effects',
  'shop.cos.equip': 'Use',
  'shop.cos.equipped': 'In use',
  'shop.cos.chapter': 'Opens when you clear chapter {n}',
  'shop.cos.reward': 'Pack or event reward',

  'shop.tickets.sub': 'Collect the rewards of a cleared stage without fighting.',
  'shop.tickets.have': '{n}/{stock} tickets',
  'shop.tickets.buy': 'Buy 1',
  'shop.tickets.ad': 'Watch an ad for {n}',
  'shop.tickets.adLeft': '{n} left today',

  'shop.need.gemsTitle': 'Not enough gems',
  'shop.need.gems': 'You need {n} more gems. Look at the gem offers?',
  'shop.need.gems.one': 'You need 1 more gem. Look at the gem offers?',
  'shop.need.goGems': 'See gems',
  'shop.need.goldTitle': 'Not enough gold',
  'shop.need.gold': 'You need {n} more gold. Earn some in battle?',
  'shop.need.goBattle': 'Go to battle',
  'shop.need.later': 'Later',
  'shop.need.unavailable': 'Gems cannot be bought on this device. Earn them in battles and missions.',

  'rewards.title': 'You got',
  'rewards.claim': 'Claim',
  'rewards.wild': '{rarity} wild card',

  'reveal.skip': 'Skip',
  'reveal.done': 'OK',
  'reveal.wild': 'Wild',
  'reveal.bonus': 'Bonus',
  'reveal.total': '{n} cards',
  'reveal.chests': '{n} chests opened',
  'reveal.wildTotal': '{n} of them wild',
  'reveal.overflow': 'Cards you can no longer use became {n} gold.',

  'odds.title': 'Chest odds',
  'odds.cards': '{n} cards',
  'odds.rows': 'Chance of each card',
  'odds.guarantee': 'Guarantee',
  'odds.pity': 'Bonus cards',
  'odds.counter': 'So far {n}/{every}',
  'odds.next': 'The chest you open next carries the bonus cards!',
  'odds.fair': 'Odds are the same whether you pay, watch an ad or neither.',
  'odds.where': 'Cats are never sold by lottery. Chests only change how fast you grow.',
});
