/**
 * The codex's words in Korean. No digit is typed here: every number is a {placeholder} that the codex's models fill from the game's
 * data tables (a test fails on a typed digit, an unfilled hole and a number nobody quotes).
 */
export const KO: Record<string, string> = {
  // ── pieces of the screen ──
  'codex.title': '도감',
  'codex.section.foes': '몬스터',
  'codex.section.toys': '장난감',
  'codex.section.cells': '발판',
  'codex.sectionLong.foes': '몬스터 도감',
  'codex.sectionLong.toys': '장난감 도감',
  'codex.sectionLong.cells': '발판 도감',
  'codex.new': '새로 만남',
  'codex.unmet': '아직 못 만났어요',
  'codex.link': '도감에서 보기',
  'codex.list': '목록',
  'codex.prev': '이전',
  'codex.next': '다음',
  'codex.settings.title': '도감',
  'codex.settings.hint': '몬스터 · 장난감 · 발판 정보를 봐요',
  'codex.settings.fresh': '새로 만난 것 {n}개',
  'codex.pause': '도감',

  // ── chapter and butler level selector ──
  'codex.chapter': '챕터',
  'codex.stake': '집사',
  'codex.basis': '챕터 {n} {name} · 집사 {stake}단계 기준',
  'codex.basis.mult': '적 체력 ×{mult}',
  'codex.basis.cut': '정예·보스 제한 시간 −{cut}초',
  'codex.basis.special': '정예·보스 체력 ×{special}',

  // ── monsters: the list ──
  'codex.group.normal': '일반 적',
  'codex.group.elite': '정예',
  'codex.group.boss': '보스',
  'codex.row.normal': '체력 {lo} ~ {hi} · 속도 {speed} · 방어 {armor}% · 저항 {ward}%',
  'codex.row.normal.one': '체력 {hp} · 속도 {speed} · 방어 {armor}% · 저항 {ward}%',
  'codex.row.normal.none': '이 챕터에는 안 나와요 · 속도 {speed} · 방어 {armor}% · 저항 {ward}%',
  'codex.row.special': '체력 {lo} ~ {hi} · 제한 {limit}초 · 방어 {armor}% · 저항 {ward}%',
  'codex.row.special.one': '체력 {lo} · 제한 {limit}초 · 방어 {armor}% · 저항 {ward}%',
  'codex.row.slow': '둔화 저항 {n}%',

  // ── monsters: a page ──
  'codex.page.traits': '특징',
  'codex.page.stats': '능력치',
  'codex.page.appears': '나오는 곳',
  'codex.page.waves': '나올 때마다',
  'codex.page.control': '제어 저항',
  'codex.page.rule': '피해 상한',
  'codex.page.ability': '능력',
  'codex.page.tips': '이렇게 잡아요',
  'codex.stat.hpMult': '오이와 비교',
  'codex.stat.hpMult.v': '오이의 ×{n}배',
  'codex.stat.hp': '체력',
  'codex.stat.hp.range': '{lo} → {hi}',
  'codex.stat.hp.note': '웨이브 {a} → {b}',
  'codex.stat.hp.none': '이 챕터에는 안 나와요',
  'codex.stat.speed': '속도',
  'codex.stat.speed.v': '{n} (오이 {base})',
  'codex.stat.armor': '방어력(물리)',
  'codex.stat.ward': '마법 저항',
  'codex.stat.slowResist': '둔화 저항',
  'codex.stat.pct': '{n}%',
  'codex.stat.reward': '처치 보상',
  'codex.stat.reward.fish': '생선 {fish}',
  'codex.stat.reward.purr': '생선 {fish} · 골골 {purr}',
  'codex.appear.row': '챕터 {n} {name}',
  'codex.appear.waves': '웨이브 {waves}',
  'codex.appear.wave': '웨이브 {waves}',
  'codex.appear.none': '어느 챕터에도 직접 나오지 않아요',
  'codex.appear.split': '{parent}이(가) 터질 때 나와요',
  'codex.target.head': '웨이브 {wave}',
  'codex.target.imagined': '웨이브 {wave} (나온다면)',
  'codex.target.hp': '체력 {hp} (오이의 ×{times}배)',
  'codex.target.limit': '제한 시간 {limit}초',
  'codex.target.limit.cut': '제한 시간 {limit}초 ({base}초에서 {cut}초 줄었어요)',
  'codex.target.cap': '초당 최대 {dps} 피해 · 최소 {min}초',
  'codex.target.note.imagined': '이 챕터에서는 다른 상대가 나와요. 나온다면 이만큼이에요.',
  'codex.target.toy': '{toy}: 제한 시간 +{seconds}초',
  'codex.control.slow': '둔화',
  'codex.control.slow.v': '{n}%까지만 들어가요',
  'codex.control.stun': '기절·얼림',
  'codex.control.stun.none': '안 통해요',
  'codex.control.stun.half': '시간이 {n}%로 줄어요',
  'codex.control.pull': '블랙홀 끌림',
  'codex.control.pull.v': '{n}%만 끌려가요',
  'codex.rule.text':
    '웨이브 {wave}처럼 제한 시간이 {limit}초면, 아무리 센 판이어도 제한 시간의 {frac}%인 {min}초는 걸려요. 몰아치기를 막으려고 초당 들어가는 피해는 최대 체력의 {per}%까지만이고, 모아 둔 힘도 {burst}초치까지만 한 번에 들어가요. 넘치는 피해는 사라져요.',

  // ── abilities ──
  'codex.ability.rage.name': '분노',
  'codex.ability.rage.text': '체력이 {hp}% 아래로 내려가면 화가 나서 능력의 재사용 시간이 {pct}% 줄어요.',
  'codex.ability.enrage.name': '화날수록 빨라져요',
  'codex.ability.enrage.text': '체력이 줄수록 걸음이 빨라져요. 체력이 바닥에 가까울 때는 최대 {pct}% 빨라져요.',
  'codex.ability.inhale.name': '들이마시기',
  'codex.ability.inhale.text': '{every}초마다 {dur}초 동안 숨을 들이마셔요. 고양이들의 공격이 느려지고, 보스가 받는 피해는 {pct}% 줄어요.',
  'codex.ability.whirl.name': '소용돌이',
  'codex.ability.whirl.text': '{every}초마다 {dur}초 동안 소용돌이를 일으켜요. 길 위의 모든 적이 {pct}% 빨라져요.',
  'codex.ability.splash.name': '물방울과 물웅덩이',
  'codex.ability.splash.text': '{every}초마다 {spawn} {count}마리를 쏟아내요. {soakEvery}초마다 고양이가 선 칸 {cells}칸을 {dur}초 동안 적셔요.',
  'codex.ability.lightning.name': '번개',
  'codex.ability.lightning.text': '{every}초마다 {side}×{side}칸 블록에 번개를 내려요. 번개는 {dur}초 동안 이어지고, 그 칸의 고양이는 공격하지 못해요.',
  'codex.ability.vaccinate.name': '예방접종',
  'codex.ability.vaccinate.text': '{every}초마다 {dur}초 동안 모든 둔화가 풀리고 새로 걸리지 않아요. 그동안 보스는 초당 최대 체력의 {pct}%씩 회복해요.',
  'codex.ability.aura_haste.name': '재촉하기',
  'codex.ability.aura_haste.text': '반경 {radius} 안의 적이 {pct}% 빨라져요.',
  'codex.ability.aura_heal.name': '치료',
  'codex.ability.aura_heal.text': '반경 {radius} 안의 적이 초당 체력 {pct}%씩 회복하고, 둔화에 걸리지 않아요.',
  'codex.ability.shield.name': '보호막',
  'codex.ability.shield.text': '최대 체력의 {pct}%만큼 보호막이 먼저 피해를 받아요.',
  'codex.ability.split.name': '분열',
  'codex.ability.split.text': '쓰러지면 {into} {count}마리로 나뉘어요.',
  'codex.ability.weaken.name': '열풍',
  'codex.ability.weaken.text': '{every}초마다 가장 센 고양이의 공격을 {dur}초 동안 절반으로 늦춰요.',
  'codex.ability.wet_pulse.name': '물 뿌리기',
  'codex.ability.wet_pulse.text': '{every}초마다 고양이가 선 칸 {cells}칸을 {dur}초 동안 적셔요. 젖은 칸의 고양이는 공격하지 못해요.',
  'codex.ability.death_burst.name': '펑!',
  'codex.ability.death_burst.text': '쓰러지면 반경 {radius} 안의 적이 {dur}초 동안 {pct}% 빨라져요.',

  // ── tips (every number comes from the enemy's own data) ──
  'codex.tip.armor': '방어력 {armor}%라서 물리 피해가 {armor}% 줄어요. 마법 피해 직업({magic})의 공격과, 방어를 깎는 고양이({breakers})가 잘 통해요. 방어 깎기와 방어 무시는 마법 저항도 같이 줄여요.',
  'codex.tip.ward': '마법 저항 {ward}%라서 마법 피해가 {ward}% 줄어요. 물리 피해 직업({physical})의 공격이 잘 통해요. 방어를 깎는 고양이({breakers})와 방어 무시(전사 시너지)는 마법 저항도 줄여요.',
  'codex.tip.open': '방어력 {armor}%, 마법 저항 {ward}%로 낮아요. 어떤 공격이든 잘 들어가요.',
  'codex.tip.stun_none': '기절과 얼림은 안 통하고, 둔화는 {slow}%까지만 들어가요. 화력으로 승부해요.',
  'codex.tip.stun_half': '기절과 얼림은 시간이 {stun}%로 줄고, 둔화는 {slow}%까지만 들어가요.',
  'codex.tip.time': '제한 시간 {limit}초인데 최소 {min}초는 걸려요. 레이저를 {dur}초 동안 두면 가장 먼저 노리고 피해도 {vuln}% 늘어요.',
  'codex.tip.enrage': '체력이 줄수록 최대 {pct}%까지 빨라져요. 앞쪽 길에서 최대한 깎아 두어요.',
  'codex.tip.inhale': '들이마시는 {dur}초 동안은 받는 피해가 {pct}% 줄어요. 그때는 레이저를 아끼고 끝난 뒤에 써요.',
  'codex.tip.whirl': '소용돌이가 {dur}초 이어지는 동안 모든 적이 {pct}% 빨라져요. 넓게 때리는 공격과 둔화로 버텨요.',
  'codex.tip.splash': '물방울이 {count}마리씩 나오니 넓게 때리는 고양이가 좋아요. 젖는 칸({cells}칸, {dur}초)의 고양이는 다른 칸으로 옮겨요.',
  'codex.tip.lightning': '번개가 {side}×{side}칸에 {dur}초 동안 떨어져요. 번쩍이는 칸의 고양이를 비켜 주어요.',
  'codex.tip.vaccinate': '{dur}초 동안 둔화가 안 통하고 보스가 초당 {pct}%씩 회복해요. 그때는 둔화에 기대지 말고 센 공격으로 눌러요.',
  'codex.tip.wet_pulse': '{every}초마다 {cells}칸이 젖어요. 반짝이는 칸의 고양이를 비켜 주어요.',
  'codex.tip.death_burst': '쓰러질 때 주변 적이 {pct}% 빨라져요. 다른 적이 가까이 없을 때 쓰러뜨려요.',

  // ── toys ──
  'codex.toys.all': '전체',
  'codex.count': '{found}/{total}개 만났어요',

  // ── board cells ──
  'codex.cellgroup.basic': '기본',
  'codex.cellgroup.special': '챕터마다 다른 특수 칸',
  'codex.cellgroup.danger': '위험한 칸',
  'codex.cellgroup.toy': '장난감 자리',
  'codex.cellgroup.aura': '도와주는 고양이',
  'codex.cellgroup.lane': '적이 걷는 길',
  'codex.cell.plain.name': '보통 칸',
  'codex.cell.plain.text': '아무 효과도 없는 칸이에요. 판은 가로 {cols}칸, 세로 {rows}칸이라 모두 {cells}칸이고, 한 칸에 고양이 한 마리가 서요. 끌어서 옮기고, 같은 고양이끼리 만나면 합쳐져요.',
  'codex.cell.special.text': '{chapter}의 특수 칸이에요. {effect} 판에 {cells}칸이 있고, 처음에는 가운데 십자 모양이에요. 스테이지가 끝날 때마다 새 자리로 옮겨요. {toy}이(가) 있으면 칸이 {toyCells}칸 늘고 효과가 이렇게 커져요. {boosted}',
  'codex.cell.wet.name': '젖은 칸',
  'codex.cell.wet.text': '물이 튄 칸이에요. 그 칸의 고양이는 물이 마를 때까지 공격하지 못해요. 칸은 닿기 {warn}초 전에 반짝여요. {spray}은(는) {sprayEvery}초마다 {sprayCells}칸을 {sprayDur}초 동안, {bath}은(는) {soakEvery}초마다 {soakCells}칸을 {soakDur}초 동안 적셔요. 고양이를 옮기면 {recover}초 뒤에 다시 공격해요. {bell}과 둘레의 고양이는 {dodge}% 확률로 피해요.',
  'codex.cell.zap.name': '낙뢰 칸',
  'codex.cell.zap.text': '번개가 떨어진 칸이에요. 젖은 칸처럼 그 칸의 고양이는 공격하지 못해요. {cloud}은(는) {every}초마다 {side}×{side}칸 블록에 번개를 내려 {dur}초 동안 이어져요. 칸은 {warn}초 먼저 반짝여요. 고양이를 옮기면 {recover}초 뒤에 다시 공격해요. {bell}과 둘레의 고양이는 {dodge}% 확률로 피해요.',
  'codex.cell.tower.name': '윗줄 칸',
  'codex.cell.tower.text': '맨 윗줄 {cells}칸이에요. {toy}이(가) 있으면 여기 선 고양이의 사거리가 {range}%, 피해가 {damage}% 늘어요.',
  'codex.cell.perch.name': '바깥 테두리 칸',
  'codex.cell.perch.text': '판 바깥을 한 바퀴 두르는 {cells}칸이에요. 길에 닿는 칸이에요. {toy}이(가) 있으면 여기 선 고양이의 공격이 {speed}% 빨라져요.',
  'codex.cell.cushion.name': '같은 직업 옆 칸',
  'codex.cell.cushion.text': '위, 아래, 양옆 {sides}칸 중 하나에 같은 직업의 고양이가 서 있는 칸이에요. {toy}이(가) 있으면 그 고양이의 피해가 {damage}% 늘어요. 직업이 다르면 늘지 않아요.',
  'codex.cell.bard.name': '악사냥 둘레 칸',
  'codex.cell.bard.text': '{cat} 둘레 {cells}칸(대각선까지)에 선 고양이는 피해가 {damage}% 늘어요. 레벨 {level}부터 더 커져서 최대 {max}%예요. 악사냥이 여럿이면 가장 센 하나만 적용돼요.',
  'codex.cell.bell.name': '방울냥 둘레 칸',
  'codex.cell.bell.text': '{cat} 둘레 {cells}칸(대각선까지)의 고양이는 공격이 {speed}% 빨라져요. 방울냥과 그 둘레의 고양이는 젖은 칸과 낙뢰 칸을 {dodge}% 확률로 피하고, 레벨 {level}부터는 최대 {dodgeMax}%까지 올라요.',
  'codex.cell.lane.name': '길',
  'codex.cell.lane.text': '적은 판 왼쪽 위의 입구로 나와 시계 방향으로 판을 빙글빙글 돌아요. {cucumber}이(가) 한 바퀴 도는 데 {lap}초쯤 걸려요. 판 가장자리 {ring}칸이 길에 닿아서 사거리가 짧은 고양이도 거기서 싸워요. 마법 고양이의 장판(눈보라, 블랙홀, 물약 구름)은 노린 적이 선 길 위에 깔려요. 길 위의 적이 {cap}마리를 넘고 {grace}초가 지나면 져요. 집사 단계가 오르면 {low}마리부터예요.',
  'codex.lane.entrance': '입구',
  'codex.lane.zone': '장판',
};
