/** The codex's words in English. Like the Korean table: no typed digit, every number is a {placeholder} filled from the game's data. */
export const EN: Record<string, string> = {
  // ── pieces of the screen ──
  'codex.title': 'Codex',
  'codex.section.foes': 'Monsters',
  'codex.section.toys': 'Toys',
  'codex.section.cells': 'Cells',
  'codex.sectionLong.foes': 'Monster codex',
  'codex.sectionLong.toys': 'Toy codex',
  'codex.sectionLong.cells': 'Board cells',
  'codex.new': 'NEW',
  'codex.unmet': 'Not met yet',
  'codex.link': 'See in codex',
  'codex.list': 'All entries',
  'codex.prev': 'Previous',
  'codex.next': 'Next',
  'codex.settings.title': 'Codex',
  'codex.settings.hint': 'Monsters, toys and board cells',
  'codex.settings.fresh': '{n} newly met',
  'codex.pause': 'Codex',

  // ── chapter and butler level selector ──
  'codex.chapter': 'Chapter',
  'codex.stake': 'Butler',
  'codex.basis': 'Chapter {n} {name}, butler level {stake}',
  'codex.basis.mult': 'Foe health x{mult}',
  'codex.basis.cut': 'Elite and boss time limit -{cut}s',
  'codex.basis.special': 'Elite and boss health x{special}',

  // ── monsters: the list ──
  'codex.group.normal': 'Common foes',
  'codex.group.elite': 'Elites',
  'codex.group.boss': 'Bosses',
  'codex.row.normal': 'HP x{hp} · Speed {speed} · Armour {armor}% · Ward {ward}%',
  'codex.row.special': 'HP {lo} to {hi} · Limit {limit}s · Armour {armor}% · Ward {ward}%',
  'codex.row.special.one': 'HP {lo} · Limit {limit}s · Armour {armor}% · Ward {ward}%',

  // ── monsters: a page ──
  'codex.page.traits': 'Traits',
  'codex.page.stats': 'Stats',
  'codex.page.appears': 'Where it comes',
  'codex.page.waves': 'Each time it comes',
  'codex.page.control': 'Control resistance',
  'codex.page.rule': 'Damage allowance',
  'codex.page.ability': 'Abilities',
  'codex.page.tips': 'How to beat it',
  'codex.stat.hpMult': 'Health multiple',
  'codex.stat.hpMult.v': '{n} times a cucumber',
  'codex.stat.hp': 'Health',
  'codex.stat.hp.range': '{lo} to {hi}',
  'codex.stat.hp.note': 'Wave {a} to wave {b}',
  'codex.stat.hp.none': 'Does not come in this chapter',
  'codex.stat.speed': 'Speed',
  'codex.stat.speed.v': '{n} (cucumber {base})',
  'codex.stat.armor': 'Armour (physical)',
  'codex.stat.ward': 'Ward (magic)',
  'codex.stat.pct': '{n}%',
  'codex.stat.reward': 'Reward',
  'codex.stat.reward.fish': 'Fish {fish}',
  'codex.stat.reward.purr': 'Fish {fish} · Purr {purr}',
  'codex.appear.row': 'Chapter {n} {name}',
  'codex.appear.waves': 'Waves {waves}',
  'codex.appear.wave': 'Wave {waves}',
  'codex.appear.none': 'Never walks a wave by itself',
  'codex.appear.split': 'Comes out when a {parent} pops',
  'codex.target.head': 'Wave {wave}',
  'codex.target.imagined': 'Wave {wave} (if it came)',
  'codex.target.hp': 'Health {hp} ({times} times a cucumber)',
  'codex.target.limit': 'Time limit {limit}s',
  'codex.target.limit.cut': 'Time limit {limit}s ({base}s cut by {cut}s)',
  'codex.target.cap': 'At most {dps} damage a second · at least {min}s',
  'codex.target.note.imagined': 'Another foe comes here in this chapter. This is what it would have.',
  'codex.target.toy': '{toy}: time limit +{seconds}s',
  'codex.control.slow': 'Slow',
  'codex.control.slow.v': 'Only up to {n}%',
  'codex.control.stun': 'Stun and freeze',
  'codex.control.stun.none': 'Do not work',
  'codex.control.stun.half': 'Last only {n}% as long',
  'codex.control.pull': 'Black hole pull',
  'codex.control.pull.v': 'Only {n}% of it',
  'codex.rule.text':
    'With a time limit of {limit}s, like wave {wave}, even the strongest board needs {min}s, which is {frac}% of the limit. To stop burst damage, at most {per}% of its health can go in per second, and saved-up strength can only be spent {burst}s at a time. Damage over that is lost.',

  // ── abilities ──
  'codex.ability.rage.name': 'Rage',
  'codex.ability.rage.text': 'Below {hp}% health it gets angry and its ability cooldowns are {pct}% shorter.',
  'codex.ability.enrage.name': 'Faster when angry',
  'codex.ability.enrage.text': 'The lower its health, the faster it walks, up to {pct}% faster near the end.',
  'codex.ability.inhale.name': 'Inhale',
  'codex.ability.inhale.text': 'Every {every}s it inhales for {dur}s. Your cats attack slower, and the boss takes {pct}% less damage.',
  'codex.ability.whirl.name': 'Whirl',
  'codex.ability.whirl.text': 'Every {every}s it whips up a whirl for {dur}s. Every enemy on the path moves {pct}% faster.',
  'codex.ability.splash.name': 'Droplets and puddles',
  'codex.ability.splash.text': 'Every {every}s it spills out {count} of the {spawn}. Every {soakEvery}s it soaks {cells} of the cells your cats stand on for {dur}s.',
  'codex.ability.lightning.name': 'Lightning',
  'codex.ability.lightning.text': 'Every {every}s lightning strikes a block of {side}×{side} cells and lasts {dur}s. Cats there cannot attack.',
  'codex.ability.vaccinate.name': 'Vaccination',
  'codex.ability.vaccinate.text': 'Every {every}s, for {dur}s, every slow is lifted and none can land. The boss heals {pct}% of its health a second meanwhile.',
  'codex.ability.aura_haste.name': 'Hurry',
  'codex.ability.aura_haste.text': 'Enemies within {radius} move {pct}% faster.',
  'codex.ability.aura_heal.name': 'Healing',
  'codex.ability.aura_heal.text': 'Enemies within {radius} heal {pct}% of their health a second and cannot be slowed.',
  'codex.ability.shield.name': 'Shield',
  'codex.ability.shield.text': 'A shield worth {pct}% of its health takes the damage first.',
  'codex.ability.split.name': 'Splitting',
  'codex.ability.split.text': 'When it falls it splits into {count} of the {into}.',
  'codex.ability.weaken.name': 'Hot air',
  'codex.ability.weaken.text': 'Every {every}s the strongest cat attacks at half speed for {dur}s.',
  'codex.ability.wet_pulse.name': 'Spraying',
  'codex.ability.wet_pulse.text': 'Every {every}s it soaks {cells} of the cells your cats stand on for {dur}s. Cats on a wet cell cannot attack.',
  'codex.ability.death_burst.name': 'Pop!',
  'codex.ability.death_burst.text': 'When it falls, enemies within {radius} move {pct}% faster for {dur}s.',

  // ── tips (every number comes from the enemy's own data) ──
  'codex.tip.armor': 'Armour {armor}% cuts physical damage by {armor}%. Armour breakers ({breakers}) and magic classes ({magic}) do best.',
  'codex.tip.ward': 'Ward {ward}% cuts magic damage by {ward}%. Physical classes ({physical}) do best.',
  'codex.tip.open': 'Armour {armor}% and ward {ward}% are low. Any attack gets through.',
  'codex.tip.stun_none': 'Stun and freeze do not work, and slows stop at {slow}%. Win with firepower.',
  'codex.tip.stun_half': 'Stun and freeze last only {stun}% as long, and slows stop at {slow}%.',
  'codex.tip.time': 'The limit is {limit}s and it takes at least {min}s. A laser held for {dur}s makes cats aim at it first, and it takes {vuln}% more damage.',
  'codex.tip.enrage': 'It speeds up as its health drops, by up to {pct}%. Wear it down early on the path.',
  'codex.tip.inhale': 'While it inhales ({dur}s) it takes {pct}% less damage. Save your laser for after.',
  'codex.tip.whirl': 'While the whirl lasts ({dur}s) every enemy is {pct}% faster. Hold on with wide attacks and slows.',
  'codex.tip.splash': '{count} droplets come at a time, so wide attacks help. Move cats off the cells about to get wet ({cells} cells, {dur}s).',
  'codex.tip.lightning': 'Lightning hits {side}×{side} cells for {dur}s. Move cats off the flashing cells.',
  'codex.tip.vaccinate': 'For {dur}s slows do not work and it heals {pct}% a second. Do not lean on slows then; push it down with strong hits.',
  'codex.tip.wet_pulse': 'Every {every}s some cells get soaked ({cells} at a time). Move cats off the flashing cells.',
  'codex.tip.death_burst': 'When it falls, nearby enemies get {pct}% faster. Finish it when no other enemy is close.',

  // ── toys ──
  'codex.toys.all': 'All',
  'codex.count': '{found} of {total} met',

  // ── board cells ──
  'codex.cellgroup.basic': 'Basics',
  'codex.cellgroup.danger': 'Dangerous cells',
  'codex.cellgroup.toy': 'Toy spots',
  'codex.cellgroup.aura': 'Helper cats',
  'codex.cellgroup.lane': 'Where enemies walk',
  'codex.cell.plain.name': 'Plain cell',
  'codex.cell.plain.text': 'A cell with no effect. The board is {cols} cells wide and {rows} deep, {cells} cells in all, and one cat stands on each. Drag cats around; two of the same cat merge.',
  'codex.cell.sun.name': 'Sunny cell',
  'codex.cell.sun.text': 'A cell the sun falls on. A cat standing there attacks {speed}% faster. The board has {cells} of them, a plus in the middle at first, and they move to new places when an act ends. The {toy} adds {toyCells} sunny cells and {toySpeed}% more speed.',
  'codex.cell.wet.name': 'Wet cell',
  'codex.cell.wet.text': 'A cell that got splashed. A cat there cannot attack until it dries. The cell flashes {warn}s before. The {spray} soaks {sprayCells} of the cells your cats stand on every {sprayEvery}s for {sprayDur}s, and the {bath} soaks {soakCells} every {soakEvery}s for {soakDur}s. A cat that is moved attacks again after {recover}s. The {bell} and the cats around it dodge it {dodge}% of the time.',
  'codex.cell.zap.name': 'Zap cell',
  'codex.cell.zap.text': 'A cell lightning struck. Like a wet cell, a cat there cannot attack. The {cloud} strikes a block of {side}×{side} cells every {every}s and it lasts {dur}s. The cells flash {warn}s before. A cat that is moved attacks again after {recover}s. The {bell} and the cats around it dodge it {dodge}% of the time.',
  'codex.cell.tower.name': 'Top row',
  'codex.cell.tower.text': 'The {cells} cells of the top row. With the {toy}, a cat standing here gets {range}% more range and {damage}% more damage.',
  'codex.cell.perch.name': 'Outer ring',
  'codex.cell.perch.text': 'The {cells} cells that run round the edge of the board, next to the lane. With the {toy}, a cat standing here attacks {speed}% faster.',
  'codex.cell.cushion.name': 'Beside the same class',
  'codex.cell.cushion.text': 'A cell with a cat of the same class standing on one of its {sides} sides. With the {toy}, that cat deals {damage}% more damage. A different class gets nothing.',
  'codex.cell.bard.name': 'Around a Bard',
  'codex.cell.bard.text': 'Cats on the {cells} cells around a {cat}, diagonals too, deal {damage}% more damage. It grows from level {level} up to {max}%. Of several bards only the strongest counts.',
  'codex.cell.bell.name': 'Around a Bell Cat',
  'codex.cell.bell.text': 'Cats on the {cells} cells around a {cat} attack {speed}% faster. The bell cat and the cats around it dodge wet and zap cells {dodge}% of the time, rising to {dodgeMax}% from level {level}.',
  'codex.cell.lane.name': 'The lane',
  'codex.cell.lane.text': 'Enemies come out of the entrance at the top left and walk clockwise round the board, lap after lap. A {cucumber} needs about {lap}s for a lap. The {ring} cells on the edge of the board touch the lane, so short-range cats fight from there. A mage cat\'s zone (blizzard, black hole, potion cloud) lands on the lane where the enemy it aimed at stands. You lose when more than {cap} enemies are on the lane for {grace}s; with a higher butler level it is {low}.',
  'codex.lane.entrance': 'Entrance',
  'codex.lane.zone': 'Zone',
};
