/**
 * The newer tracks, written in the score language of compose.ts: one per chapter place (kitchen, bathroom, garden, vet clinic), the gold
 * dungeon, the tension track of an elite wave, the second menu track and the two that loop under the result screen. The living room is the
 * original `battle` score, the boss the original `boss` score. Every chapter track is 16 bars in four sections (the tune, its variation, a
 * contrasting bridge with less in it, a full return with a fill into the loop) and has four intensity layers like `battle`:
 *   layer 0 bass, kick, shaker or hats and the place's own percussion; layer 1 pad, chords and arpeggio; layer 2 the tune and the snare;
 *   layer 3 the tune an octave up, open hats, ornaments, the bell-tree and the toms.
 */
import { compose } from './compose';
import { Inst } from './scores';

const LAYER_EDGES = [0.25, 0.5, 0.75];
/** A bar-long pattern that only has its first beat: the bell tree on a downbeat. */
const DOWNBEAT = 'X...............';
/** The falling four-tom fill of the last beat of a bar, for a `pool` lane of four tom notes. */
const TOM_RUN = '............0123';

// ------------------------------------------------------------------ KITCHEN (Bb major, 120 BPM): bouncy, pots and pans

export const KITCHEN = compose({
  id: 'kitchen',
  bpm: 120,
  swing: 0.12,
  layers: 4,
  layerEdges: LAYER_EDGES,
  chords: 'Bb Bb Eb F7 Bb Gm Eb F7 Cm F7 Bb Gm Eb F7 Bb F7',
  lanes: [
    { kind: 'bass', inst: Inst.bass, layer: 0, pats: ['R..o..f.R..o..f.', 'R..o..f.R..o..f.', 'R...t...f...t...', 'R..o..f.R..o.tf.'], dur: 0.75 },
    { kind: 'hit', inst: Inst.kick, layer: 0, midi: 36, pats: ['x.....x.x.......', 'x.....x.x...x...', 'x.......x.......', 'x...x...x.x.x...'], bars: { 15: 'x.......x.x.x...' } },
    { kind: 'hit', inst: Inst.shaker, layer: 0, midi: 60, vel: 0.8, pats: ['..o...o...o...o.', 'g.x.g.x.g.x.g.x.', 'g.x.g.x.g.x.g.x.', 'g.x.g.x.g.x.g.x.'] },
    { kind: 'hit', inst: Inst.perc, layer: 0, midi: 70, vel: 0.9, pats: ['....x.......x...', '....x.....o.x...', '....o.o.o.o.o...', '....x.......x...'] },
    { kind: 'comp', inst: Inst.chord, layer: 1, low: 55, pats: ['....x..o....x..o', '..o.x..o..o.x..o', 'x.......x.......', '..x...o...x...o.'], vel: 0.8 },
    { kind: 'comp', inst: Inst.pad, layer: 1, low: 48, pats: [DOWNBEAT], dur: 13, vel: 0.55 },
    { kind: 'hit', inst: Inst.perc2, layer: 1, midi: 84, vel: 0.7, pats: ['..x...o...x...o.', '..x...o...x...o.', '................', 'x.x.x.x.x.x.x.x.'] },
    { kind: 'arp', inst: Inst.arp, layer: 1, low: 60, pats: ['................', '................', '0.2.1.2.0.2.1.2.', '................'], bars: { 12: '0...2...1...2...', 13: '0...2...1...2...' } },
    { kind: 'hit', inst: Inst.snare, layer: 2, midi: 60, pats: ['....X.......X...', '....X.......X...', '................', '....X.....g.X.g.'] },
    {
      kind: 'tune',
      inst: Inst.lead,
      layer: 2,
      vel: 0.8,
      double: { inst: Inst.lead2, layer: 3, shift: 12, vel: 0.4, minDur: 3 },
      tune: [
        'Bb5:3 D6:1 F6:2 D6:2 C6:3 Bb5:1 r:2 F5:2',
        'D6:3 Bb5:1 F5:2 Bb5:2 D6:6 r:2',
        'G5:3 Bb5:1 Eb6:2 Bb5:2 G5:3 Bb5:1 r:2 Eb5:2',
        'A5:2 C6:2 Eb6:2 C6:2 A5:4 F5:2 A5:2',
        'Bb5:3 D6:1 F6:2 D6:2 C6:3 Bb5:1 D6:4',
        'G5:3 Bb5:1 D6:2 Bb5:2 G5:6 r:2',
        'Eb6:3 D6:1 C6:2 Bb5:2 G5:3 Bb5:1 Eb6:4',
        'C6:2 A5:2 F5:2 A5:2 C6:4 r:4',
        'C6:2 Eb6:2 G6:4 F6:2 Eb6:2 C6:4',
        'A5:2 C6:2 F6:4 Eb6:2 C6:2 A5:4',
        'D6:2 F6:2 A6:4 G6:2 F6:2 D6:4',
        'G5:2 Bb5:2 D6:2 G6:2 F6:2 D6:2 Bb5:4',
        'Eb6:3 D6:1 Eb6:2 G6:2 F6:3 Eb6:1 D6:4',
        'C6:3 A5:1 C6:2 F6:2 Eb6:3 C6:1 A5:4',
        'D6:3 F6:1 A6:2 F6:2 D6:3 Bb5:1 F5:4',
        'C6:2 Eb6:2 A5:2 C6:2 F5:2 A5:2 C6:4',
      ],
    },
    { kind: 'hit', inst: Inst.openHat, layer: 3, midi: 80, pats: ['................', '......o.......o.', '................', '......o.....o...'] },
    { kind: 'hit', inst: Inst.crash, layer: 3, midi: 76, vel: 0.7, dur: 8, bars: { 0: DOWNBEAT, 4: DOWNBEAT, 12: DOWNBEAT } },
    { kind: 'pool', inst: Inst.tom, layer: 3, pool: ['G4', 'Eb4', 'C4', 'G3'], vel: 0.75, dur: 2, bars: { 3: TOM_RUN, 7: TOM_RUN } },
  ],
});

// ------------------------------------------------------------------ BATHROOM (Eb major, 104 BPM): watery, plucked, bubbly

export const BATH = compose({
  id: 'bath',
  bpm: 104,
  swing: 0.28,
  layers: 4,
  layerEdges: LAYER_EDGES,
  chords: 'Eb Eb Ab Bb Eb Cm Ab Bb Fm Bb Eb Cm Ab Bb Eb Bb',
  lanes: [
    { kind: 'bass', inst: Inst.bass, layer: 0, pats: ['R.....o.f.......', 'R.....o.f...t...', 'R...............', 'R.....o.R.....f.'], dur: 0.9 },
    { kind: 'hit', inst: Inst.kick, layer: 0, midi: 36, pats: ['x.......x.......', 'x.......x.....x.', '................', 'x.......x.x.....'] },
    { kind: 'hit', inst: Inst.shaker, layer: 0, midi: 60, vel: 0.8, pats: ['..o...o...o...o.', 'g.o.g.o.g.o.g.o.', '..g...g...g...g.', 'g.o.g.o.g.o.g.o.'] },
    { kind: 'hit', inst: Inst.perc, layer: 0, midi: 72, pats: ['.o.....o....o...', '.o...o..o....o..', '..o.....o.......', 'o.....o.o....o..'] },
    { kind: 'comp', inst: Inst.chord, layer: 1, low: 51, pats: ['x.......o.......', 'x.......o.......', 'x...............', 'x.......x.......'], dur: 4, vel: 0.8 },
    { kind: 'comp', inst: Inst.pad, layer: 1, low: 51, pats: [DOWNBEAT], dur: 13, vel: 0.6 },
    { kind: 'hit', inst: Inst.perc2, layer: 1, midi: 88, vel: 0.8, pats: ['...x.......o....', '...x...o...x....', '.......o........', '....x.......x...'] },
    { kind: 'arp', inst: Inst.arp, layer: 1, low: 63, dur: 1, pats: ['................', '0...1...2...1...', '0...2...1...3...', '0.1.2...3.2.1...'] },
    { kind: 'hit', inst: Inst.snare, layer: 2, midi: 60, pats: ['................', '....x.......x...', '................', '....x.......x...'] },
    {
      kind: 'tune',
      inst: Inst.lead,
      layer: 2,
      vel: 0.8,
      double: { inst: Inst.lead2, layer: 3, shift: 12, vel: 0.4, minDur: 3 },
      tune: [
        'G5:2 Bb5:2 Eb6:4 D6:2 Bb5:2 G5:4',
        'Bb5:2 G5:2 Eb5:4 r:2 G5:2 Bb5:4',
        'C6:2 Eb6:2 Ab6:4 G6:2 Eb6:2 C6:4',
        'D6:2 F6:2 D6:4 Bb5:2 F5:2 Bb5:4',
        'G5:2 Bb5:2 Eb6:4 G6:2 F6:2 Eb6:4',
        'Eb6:2 C6:2 G5:4 r:2 C6:2 Eb6:4',
        'C6:2 Eb6:2 Ab5:4 C6:2 Eb6:2 Ab6:4',
        'F6:2 D6:2 Bb5:4 F5:2 Bb5:2 D6:4',
        'C6:6 Ab5:2 F5:4 r:4',
        'D6:6 Bb5:2 F5:4 r:4',
        'G5:4 Bb5:4 Eb6:8',
        'Eb6:4 C6:4 G5:4 r:4',
        'C6:2 Eb6:2 Ab6:4 G6:2 Eb6:2 C6:2 Eb6:2',
        'D6:2 F6:2 Bb5:2 D6:2 F6:4 D6:4',
        'G5:2 Bb5:2 Eb6:2 G6:2 F6:2 Eb6:2 D6:4',
        'F6:2 D6:2 Bb5:2 F5:2 D6:2 F6:2 Bb5:4',
      ],
    },
    { kind: 'pool', inst: Inst.orn, layer: 3, pool: ['C5', 'E5', 'G5', 'C6'], pats: ['..........0.....', '......1....0....', '..2.........3...', '..1...0..2......'], vel: 0.8 },
    { kind: 'hit', inst: Inst.openHat, layer: 3, midi: 80, pats: ['................', '......o.......o.', '................', '......o.......o.'] },
    { kind: 'hit', inst: Inst.crash, layer: 3, midi: 76, vel: 0.7, dur: 8, bars: { 0: DOWNBEAT, 4: DOWNBEAT, 12: DOWNBEAT } },
    { kind: 'pool', inst: Inst.tom, layer: 3, pool: ['Bb4', 'G4', 'Eb4', 'Bb3'], vel: 0.7, dur: 2, bars: { 3: TOM_RUN, 7: TOM_RUN } },
  ],
});

// ------------------------------------------------------------------ GARDEN (D major, 112 BPM): airy, a flute, birds

export const GARDEN = compose({
  id: 'garden',
  bpm: 112,
  swing: 0.1,
  layers: 4,
  layerEdges: LAYER_EDGES,
  chords: 'D A Bm G D A G A Bm G D A G A D A',
  lanes: [
    { kind: 'bass', inst: Inst.bass, layer: 0, pats: ['R.......f.......', 'R.......f.....t.', 'R...............', 'R.......f...o...'], dur: 0.9 },
    { kind: 'hit', inst: Inst.kick, layer: 0, midi: 36, pats: ['x...............', 'x.......x.......', '................', 'x.......x...x...'] },
    { kind: 'hit', inst: Inst.shaker, layer: 0, midi: 60, vel: 0.8, pats: ['g.o.g.o.g.o.g.o.', 'g.o.g.o.g.o.g.o.', '..g...g...g...g.', 'g.o.g.o.g.o.g.o.'] },
    { kind: 'hit', inst: Inst.perc, layer: 0, midi: 60, pats: ['................', '....o.......o...', '....o.......o...', '....o.o.....o...'] },
    { kind: 'comp', inst: Inst.chord, layer: 1, low: 55, dur: 3, pats: ['x.......o.......', 'x...o...x...o...', 'x...............', 'x...o...x...o...'], vel: 0.8 },
    { kind: 'comp', inst: Inst.pad, layer: 1, low: 57, pats: [DOWNBEAT], dur: 13, vel: 0.65 },
    { kind: 'arp', inst: Inst.arp, layer: 1, low: 62, pats: ['0...1...2...1...', '0...2...1...2...', '0...2...1...3...', '0...2...1...3...'] },
    { kind: 'hit', inst: Inst.snare, layer: 2, midi: 60, pats: ['................', '....o.......o...', '................', '....x.......x...'] },
    {
      kind: 'tune',
      inst: Inst.lead,
      layer: 2,
      vel: 0.85,
      double: { inst: Inst.lead2, layer: 3, shift: 12, vel: 0.35, minDur: 3 },
      tune: [
        'F#5:4 A5:4 D6:6 r:2',
        'C#6:4 B5:2 A5:2 E6:6 r:2',
        'B5:4 D6:4 F#6:6 r:2',
        'E6:4 D6:2 B5:2 G5:6 r:2',
        'F#5:4 A5:4 D6:4 E6:2 F#6:2',
        'E6:4 C#6:4 A5:6 r:2',
        'B5:4 D6:4 G6:4 F#6:2 E6:2',
        'E6:2 C#6:2 A5:4 E5:4 r:4',
        'D6:3 F#6:3 B5:2 D6:2 F#6:6',
        'G6:3 E6:3 B5:2 D6:2 G5:6',
        'F#6:3 A6:3 F#6:2 D6:2 A5:6',
        'C#6:3 E6:3 A5:2 C#6:2 E6:6',
        'B5:2 D6:2 G6:4 F#6:2 E6:2 D6:4',
        'C#6:2 E6:2 A6:4 F#6:2 E6:2 C#6:2 r:2',
        'D6:2 F#6:2 A6:4 F#6:2 D6:2 F#6:4',
        'E6:4 C#6:2 A5:2 E5:4 r:4',
      ],
    },
    { kind: 'pool', inst: Inst.orn, layer: 3, pool: ['B6', 'D7', 'E7', 'F#7'], pats: ['..........0.....', '..1.........0...', '.2.......3......', '...0....1...2...'], vel: 0.9 },
    { kind: 'hit', inst: Inst.crash, layer: 3, midi: 76, vel: 0.7, dur: 8, bars: { 0: DOWNBEAT, 4: DOWNBEAT, 12: DOWNBEAT } },
    { kind: 'pool', inst: Inst.tom, layer: 3, pool: ['A4', 'F#4', 'D4', 'A3'], vel: 0.6, dur: 2, bars: { 7: TOM_RUN, 11: TOM_RUN } },
  ],
});

// ------------------------------------------------------------------ VET CLINIC (A minor, 124 BPM): tense but cute, a clock

export const CLINIC = compose({
  id: 'clinic',
  bpm: 124,
  layers: 4,
  layerEdges: LAYER_EDGES,
  chords: 'Am Am F E7 Am Dm F E7 Bdim E7 Am F Dm E7 Am E7',
  lanes: [
    { kind: 'bass', inst: Inst.bass, layer: 0, pats: ['R.....t.f.....t.', 'R...t...f...t.f.', 'R...............', 'R..rt..tf..ft.r.'], dur: 0.6 },
    { kind: 'hit', inst: Inst.kick, layer: 0, midi: 36, pats: ['x.......x.......', 'x.......x.....x.', '................', 'x...x...x...x...'] },
    { kind: 'hit', inst: Inst.shaker, layer: 0, midi: 60, vel: 0.8, pats: ['................', '..o...o...o...o.', 'o.o.o.o.o.o.o.o.', '..x...x...x...x.'] },
    { kind: 'hit', inst: Inst.perc, layer: 0, midi: 60, pats: ['x.......x.......', 'x.......x.......', 'x.x.x.x.x.x.x.x.', 'x.......x.......'], vel: 0.9 },
    { kind: 'hit', inst: Inst.perc2, layer: 0, midi: 60, pats: ['....x.......x...', '....x.......x...', '....x.......x.x.', '....x.......x...'], vel: 0.9 },
    { kind: 'comp', inst: Inst.stab, layer: 1, low: 57, pats: ['..x.....x.......', '..x...o...x...o.', '................', '..x...x...x...x.'] },
    { kind: 'comp', inst: Inst.pad, layer: 1, low: 48, pats: [DOWNBEAT], dur: 13, vel: 0.55 },
    { kind: 'arp', inst: Inst.arp, layer: 1, low: 69, dur: 1, pats: ['................', '0...2...1...2...', '0.1.2.1.0.1.2.1.', '0.1.2.1.0.1.2.1.'] },
    { kind: 'hit', inst: Inst.snare, layer: 2, midi: 60, pats: ['................', '....o.......o...', '................', '....x.......x...'] },
    {
      kind: 'tune',
      inst: Inst.lead,
      layer: 2,
      vel: 0.8,
      double: { inst: Inst.lead2, layer: 3, shift: 12, vel: 0.35, minDur: 3 },
      tune: [
        'A5:2 C6:2 E6:2 C6:2 B5:2 A5:2 r:4',
        'A5:2 C6:2 E6:2 A6:2 G6:2 E6:2 r:4',
        'F6:2 E6:2 C6:2 A5:2 F5:4 r:4',
        'E6:2 D6:2 B5:2 G#5:2 B5:2 E6:2 r:4',
        'A5:2 C6:2 E6:2 C6:2 B5:2 A5:2 C6:2 E6:2',
        'D6:2 F6:2 A6:2 F6:2 E6:2 D6:2 r:4',
        'C6:2 F6:2 A5:2 C6:2 F6:4 r:4',
        'B5:2 D6:2 E6:2 D6:2 B5:2 G#5:2 E5:4',
        'B5:2 D6:2 F6:2 D6:2 B5:2 D6:2 F6:4',
        'G#5:2 B5:2 E6:2 B5:2 G#5:2 B5:2 E6:4',
        'A5:2 C6:2 E6:2 A6:2 E6:2 C6:2 A5:4',
        'F5:2 A5:2 C6:2 F6:2 E6:2 C6:2 A5:4',
        'D6:3 F6:1 A6:2 F6:2 D6:3 A5:1 D6:4',
        'E6:3 G#5:1 B5:2 E6:2 D6:3 B5:1 G#5:4',
        'A5:2 C6:2 E6:4 A6:4 E6:2 C6:2',
        'D6:2 B5:2 G#5:2 B5:2 D6:2 E6:2 G#5:4',
      ],
    },
    { kind: 'hit', inst: Inst.openHat, layer: 3, midi: 80, pats: ['................', '......o.......o.', '................', '..o...o...o...o.'] },
    { kind: 'pool', inst: Inst.orn, layer: 3, pool: ['A6', 'C7', 'E7'], pats: ['.......0........', '...1.......0....', '..2.....1.......', '.0.....1....2...'], vel: 0.8 },
    { kind: 'hit', inst: Inst.crash, layer: 3, midi: 76, vel: 0.6, dur: 8, bars: { 0: DOWNBEAT, 12: DOWNBEAT } },
    { kind: 'pool', inst: Inst.tom, layer: 3, pool: ['E4', 'D4', 'B3', 'A3'], vel: 0.6, dur: 2, bars: { 3: TOM_RUN, 7: TOM_RUN, 11: TOM_RUN } },
  ],
});

// ------------------------------------------------------------------ GOLD DUNGEON (A major, 152 BPM): bright, coins, fast

export const GOLD = compose({
  id: 'gold',
  bpm: 152,
  swing: 0.08,
  layers: 4,
  layerEdges: LAYER_EDGES,
  chords: 'A E F#m D A E D E F#m D A E D E A E',
  lanes: [
    { kind: 'bass', inst: Inst.bass, layer: 0, pats: ['R..o..f.R..o..f.', 'R.o.f.o.R.o.f.o.', 'R...R...f...f...', 'R.o.f.o.R.o.f.o.'], dur: 0.7 },
    { kind: 'hit', inst: Inst.kick, layer: 0, midi: 36, pats: ['x.......x.......', 'x...x...x...x...', '................', 'x...x...x...x...'] },
    { kind: 'hit', inst: Inst.hat, layer: 0, midi: 80, vel: 0.7, pats: ['x.o.x.o.x.o.x.o.', 'x.o.x.o.x.o.x.o.', 'o.o.o.o.o.o.o.o.', 'x.x.x.x.x.x.x.x.'] },
    { kind: 'hit', inst: Inst.perc, layer: 0, midi: 84, pats: ['....o.......o...', '..x...o...x.....', '..o...o...o.....', '..x...x...x.....'], vel: 0.8 },
    { kind: 'comp', inst: Inst.chord, layer: 1, low: 57, pats: ['....x.......x...', '..x...x...x...x.', 'x.......x.......', '....x.......x...'], vel: 0.8 },
    { kind: 'comp', inst: Inst.pad, layer: 1, low: 48, pats: [DOWNBEAT], dur: 12.5, vel: 0.55 },
    { kind: 'arp', inst: Inst.arp, layer: 1, low: 64, dur: 1, pats: ['....1...2...1...', '....1...2...1...', '....2...1...3...', '................'] },
    { kind: 'hit', inst: Inst.snare, layer: 2, midi: 60, pats: ['....X.......X...', '....X.......X...', '................', '....X.....g.X.g.'] },
    {
      kind: 'tune',
      inst: Inst.lead,
      layer: 2,
      vel: 0.8,
      double: { inst: Inst.lead2, layer: 3, shift: 12, vel: 0.35, minDur: 4 },
      tune: [
        'A5:2 C#6:2 E6:2 A6:2 E6:2 C#6:2 A5:4',
        'G#5:2 B5:2 E6:2 G#6:2 E6:2 B5:2 G#5:4',
        'F#5:2 A5:2 C#6:2 F#6:2 C#6:2 A5:2 F#5:4',
        'D6:2 F#6:2 A6:2 F#6:2 D6:4 A5:2 D6:2',
        'A5:2 C#6:2 E6:2 A6:2 G#6:2 E6:2 C#6:4',
        'B5:2 E6:2 G#6:2 E6:2 B5:2 G#5:2 B5:4',
        'D6:2 F#6:2 A6:2 F#6:2 E6:2 D6:2 A5:4',
        'G#5:2 B5:2 E6:2 B5:2 G#6:4 E6:4',
        'C#6:3 A5:1 F#5:2 A5:2 C#6:4 F#6:4',
        'D6:3 A5:1 F#5:2 A5:2 D6:4 F#6:4',
        'E6:3 C#6:1 A5:2 C#6:2 E6:4 A6:4',
        'G#6:3 E6:1 B5:2 E6:2 G#5:4 B5:4',
        'A6:2 F#6:2 D6:2 F#6:2 A6:2 F#6:2 D6:4',
        'G#6:2 E6:2 B5:2 E6:2 G#6:2 E6:2 B5:4',
        'A5:2 C#6:2 E6:2 A6:2 E6:2 C#6:2 A6:4',
        'B5:2 G#5:2 E5:2 G#5:2 B5:2 E6:2 G#6:4',
      ],
    },
    { kind: 'hit', inst: Inst.openHat, layer: 3, midi: 80, pats: ['................', '.......o...o....', '................', '.......o...o....'] },
    { kind: 'pool', inst: Inst.orn, layer: 3, pool: ['E5', 'A5', 'C#6'], pats: ['..........0.....', '.......1....0...', '..2.....1.......', '................'], vel: 0.9 },
    { kind: 'hit', inst: Inst.crash, layer: 3, midi: 76, vel: 0.7, dur: 8, bars: { 0: DOWNBEAT, 4: DOWNBEAT, 12: DOWNBEAT } },
    { kind: 'pool', inst: Inst.tom, layer: 3, pool: ['E4', 'C#4', 'B3', 'A3'], vel: 0.7, dur: 2, bars: { 7: TOM_RUN, 15: TOM_RUN } },
  ],
});

// ------------------------------------------------------------------ ELITE WAVE (D minor, 116 BPM): tension; three layers

export const ELITE = compose({
  id: 'elite',
  bpm: 116,
  layers: 3,
  layerEdges: [0.3, 0.65],
  chords: 'Dm Dm Bb A Dm Gm Bb A Dm Dm Gm A Bb A Dm A',
  lanes: [
    { kind: 'bass', inst: Inst.bass, layer: 0, pats: ['R...R...R...R...', 'R.r.R.r.R.r.R.r.', 'R...............', 'R.r.R.r.R.r.R.rr'], dur: 0.7 },
    { kind: 'hit', inst: Inst.kick, layer: 0, midi: 36, pats: ['x.....x.........', 'x.....x.x.....x.', 'x.....x.........', 'x...x...x...x...'] },
    { kind: 'hit', inst: Inst.shaker, layer: 0, midi: 60, vel: 0.8, pats: ['..o...o...o...o.', 'o.o.o.o.o.o.o.o.', '................', 'o.o.o.o.o.o.o.o.'] },
    { kind: 'hit', inst: Inst.perc, layer: 0, midi: 60, vel: 0.9, pats: ['x.......x.......', 'x...x...x...x...', 'x.......x.......', 'x...x...x...x...'] },
    { kind: 'hit', inst: Inst.perc2, layer: 0, midi: 60, vel: 0.9, pats: ['....x.......x...', '..x...x...x...x.', '....x.......x...', '..x...x...x...x.'] },
    { kind: 'comp', inst: Inst.stab, layer: 1, low: 50, pats: ['x..x..x.........', 'x..x..x...x.....', '................', 'x..x..x...x..x..'] },
    { kind: 'comp', inst: Inst.pad, layer: 1, low: 45, pats: [DOWNBEAT], dur: 13, vel: 0.6 },
    { kind: 'arp', inst: Inst.arp, layer: 1, low: 62, dur: 1, pats: ['0...2...1...2...', '0.2.1.2.0.2.1.2.', '0...2...1...2...', '0.2.1.2.0.2.1.2.'] },
    { kind: 'hit', inst: Inst.snare, layer: 2, midi: 60, pats: ['................', '....x.......x...', '................', '....X.......X...'], bars: { 11: 'o.o.x.x.xxxxXXXX' } },
    {
      kind: 'tune',
      inst: Inst.lead,
      layer: 2,
      vel: 0.8,
      double: { inst: Inst.lead2, layer: 2, shift: 12, vel: 0.35, minDur: 3 },
      tune: [
        'D5:2 F5:2 A5:2 F5:2 D5:2 r:2 A4:4',
        'D5:2 F5:2 A5:2 F5:2 E5:2 r:2 D5:4',
        'Bb4:2 D5:2 F5:2 D5:2 Bb4:2 r:2 F4:4',
        'A4:2 C#5:2 E5:2 C#5:2 A4:2 r:2 E5:4',
        'D5:2 F5:2 A5:2 D6:2 C6:2 A5:2 F5:4',
        'G5:2 Bb5:2 D6:2 Bb5:2 G5:2 r:2 D5:4',
        'Bb5:2 D6:2 F6:2 D6:2 Bb5:2 r:2 F5:4',
        'A5:2 C#6:2 E6:2 C#6:2 A5:2 r:2 E5:4',
        'D5:8 r:8',
        'A4:4 r:4 D5:4 r:4',
        'G4:4 r:4 Bb4:4 r:4',
        'A4:2 A4:2 A4:2 r:2 C#5:2 E5:2 A5:4',
        'D6:2 Bb5:2 F5:2 Bb5:2 D6:4 r:4',
        'E6:2 C#6:2 A5:2 C#6:2 E6:4 r:4',
        'D6:2 A5:2 F5:2 A5:2 D6:4 F6:4',
        'E6:2 C#6:2 A5:2 E5:2 A5:2 C#6:2 E6:4',
      ],
    },
    { kind: 'pool', inst: Inst.tom, layer: 2, pool: ['A4', 'F4', 'D4', 'A3'], vel: 0.8, dur: 2, bars: { 3: TOM_RUN, 7: TOM_RUN, 15: TOM_RUN } },
    { kind: 'hit', inst: Inst.crash, layer: 2, midi: 76, vel: 0.7, dur: 8, bars: { 0: DOWNBEAT, 4: DOWNBEAT, 12: DOWNBEAT } },
  ],
});

// ------------------------------------------------------------------ HOME 2 (F major, 88 BPM): the second menu track

export const HOME2 = compose({
  id: 'home2',
  bpm: 88,
  swing: 0.14,
  layers: 1,
  chords: 'F Dm Bb C F Dm Bb C Gm C F Dm Bb C F C',
  then: 'home',
  lanes: [
    { kind: 'bass', inst: Inst.bass, layer: 0, pats: ['R.....f.........', 'R.....f.r.....f.', 'R...f...r...f...', 'R.....f.r.....w.'], dur: 0.85 },
    { kind: 'hit', inst: Inst.kick, layer: 0, midi: 36, pats: ['................', 'x.......x.......', 'x.......x.x.....', 'x.......x.......'] },
    { kind: 'hit', inst: Inst.rim, layer: 0, midi: 76, vel: 0.7, pats: ['................', '....o.......o...', '....o.......o...', '....o.......o...'] },
    { kind: 'hit', inst: Inst.shaker, layer: 0, midi: 60, vel: 0.8, pats: ['..o...o...o...o.', 'g.x.g.x.g.x.g.x.', 'g.x.g.x.g.x.g.x.', 'g.x.g.x.g.x.g.x.'] },
    { kind: 'comp', inst: Inst.pad, layer: 0, low: 48, pats: [DOWNBEAT], dur: 15.5, vel: 0.6 },
    { kind: 'comp', inst: Inst.chord, layer: 0, low: 53, dur: 3, pats: ['x.....o...x...o.', 'x..o..x...x..o..', 'x.......x...o...', 'x..o..x...x..o..'], vel: 0.8 },
    { kind: 'arp', inst: Inst.arp, layer: 0, low: 60, pats: ['................'], bars: { 8: '0.1.2.1.0.1.2.1.', 9: '0.1.2.1.0.1.2.1.', 10: '0.1.2.1.0.1.2.1.', 11: '0.1.2.1.0.1.2.1.', 12: '0.1.2.1.0.1.2.1.', 13: '0.1.2.1.0.1.2.1.' } },
    { kind: 'pool', inst: Inst.tom, layer: 0, pool: ['A4', 'G4', 'E4', 'D4'], vel: 0.5, dur: 2, bars: { 15: TOM_RUN } },
    {
      kind: 'tune',
      inst: Inst.lead,
      layer: 0,
      vel: 0.75,
      tune: [
        'C6:3 A5:3 F5:2 G5:2 A5:6',
        'D6:3 A5:3 F5:2 A5:2 D6:6',
        'Bb5:3 D6:3 F6:2 D6:2 C6:6',
        'G5:3 C6:3 E6:2 C6:2 G5:6',
        'A5:3 C6:3 F6:2 E6:2 C6:6',
        'F6:3 D6:3 A5:2 D6:2 F6:6',
        'D6:3 Bb5:3 F5:2 Bb5:2 D6:6',
        'E6:3 C6:3 G5:2 C6:2 E6:4 D6:2',
        'G5:4 Bb5:4 D6:4 C6:4',
        'E6:4 D6:4 C6:4 G5:4',
        'A5:4 C6:4 F6:4 E6:4',
        'D6:4 F6:4 A5:4 D6:4',
        'D6:3 F6:3 Bb5:2 D6:2 F6:6',
        'E6:3 G5:3 C6:2 E6:2 G6:6',
        'A5:2 C6:2 F6:4 E6:2 D6:2 C6:4',
        'G5:3 E5:3 G5:2 C6:2 D6:2 E6:4',
      ],
    },
  ],
});

// ------------------------------------------------------------------ RESULT: victory (C major, 108 BPM) and defeat (E minor, 72 BPM)

export const WIN = compose({
  id: 'win',
  bpm: 108,
  swing: 0.1,
  layers: 1,
  chords: 'C G Am F C G F G Am F C G F G C G',
  lanes: [
    { kind: 'bass', inst: Inst.bass, layer: 0, pats: ['R.......f.......', 'R.....f.R.....f.', 'R.......R.......', 'R.....f.R.....o.'], dur: 0.9 },
    { kind: 'hit', inst: Inst.kick, layer: 0, midi: 36, pats: ['x...............', 'x.......x.......', 'x...x...x...x...', 'x.......x...x...'] },
    { kind: 'hit', inst: Inst.shaker, layer: 0, midi: 60, vel: 0.8, pats: ['..o...o...o...o.', 'g.o.g.o.g.o.g.o.', 'g.x.g.x.g.x.g.x.', 'g.x.g.x.g.x.g.x.'] },
    { kind: 'hit', inst: Inst.snare, layer: 0, midi: 60, pats: ['................', '................', '....o.......o...', '....o.......o...'] },
    { kind: 'comp', inst: Inst.pad, layer: 0, low: 48, pats: [DOWNBEAT], dur: 15.5, vel: 0.6 },
    { kind: 'comp', inst: Inst.chord, layer: 0, low: 55, dur: 3, pats: ['x.......o.......', 'x...o...x...o...', 'x...o...x...o...', 'x...o...x...o...'], vel: 0.8 },
    { kind: 'arp', inst: Inst.arp, layer: 0, low: 60, pats: ['................', '0...1...2...1...', '0...1...2...1...', '0...2...1...3...'] },
    { kind: 'pool', inst: Inst.orn, layer: 0, pool: ['C6', 'E6', 'G6'], pats: ['................', '..............0.', '......1.......2.', '..0...1...2...0.'], vel: 0.8 },
    { kind: 'hit', inst: Inst.crash, layer: 0, midi: 76, vel: 0.6, dur: 8, bars: { 0: DOWNBEAT, 4: DOWNBEAT, 12: DOWNBEAT } },
    {
      kind: 'tune',
      inst: Inst.lead,
      layer: 0,
      vel: 0.8,
      tune: [
        'E5:2 G5:2 C6:4 G5:2 E5:2 G5:4',
        'D5:2 G5:2 B5:4 G5:2 D5:2 G5:4',
        'E5:2 A5:2 C6:4 A5:2 E5:2 A5:4',
        'F5:2 A5:2 C6:4 A5:2 G5:2 F5:4',
        'G5:3 C6:3 E6:2 D6:2 C6:6',
        'B5:3 D6:3 G6:2 E6:2 D6:6',
        'A5:3 C6:3 F6:2 E6:2 C6:6',
        'B5:2 D6:2 G6:4 F6:2 D6:2 B5:4',
        'C6:4 E6:4 A5:4 C6:4',
        'A5:4 C6:4 F6:4 A5:4',
        'G5:4 C6:4 E6:4 G6:4',
        'D6:4 B5:4 G5:4 D6:4',
        'A5:2 C6:2 F6:4 C6:2 A5:2 F5:4',
        'B5:2 D6:2 G6:4 D6:2 B5:2 G5:4',
        'E6:3 G6:3 C6:2 E6:2 G6:6',
        'D6:4 B5:2 D6:2 G6:8',
      ],
    },
  ],
});

export const LOSE = compose({
  id: 'lose',
  bpm: 72,
  layers: 1,
  chords: 'Em Em C D Em Am C D C D Em Am C D Em Em',
  lanes: [
    { kind: 'bass', inst: Inst.bass, layer: 0, pats: ['R...............', 'R.......f.......', 'R...............', 'R.......f.......'], dur: 0.95 },
    { kind: 'hit', inst: Inst.kick, layer: 0, midi: 36, pats: ['x.....x.........', '................', 'x.....x.........', 'x.....x.....x...'] },
    { kind: 'hit', inst: Inst.shaker, layer: 0, midi: 60, vel: 0.7, pats: ['................', '..g.....g.......', '................', '..g.....g.....g.'] },
    { kind: 'comp', inst: Inst.pad, layer: 0, low: 48, pats: [DOWNBEAT], dur: 15.5, vel: 0.7 },
    { kind: 'comp', inst: Inst.chord, layer: 0, low: 52, dur: 8, pats: ['x...............', 'x...............', 'x.......o.......', 'x.......o.......'], vel: 0.7 },
    { kind: 'arp', inst: Inst.arp, layer: 0, low: 64, dur: 3, pats: ['................', '0...2...1...2...', '................', '0...2...1...2...'] },
    { kind: 'pool', inst: Inst.orn, layer: 0, pool: ['E6', 'B6'], pats: ['................', '......0.........', '................', '..........1.....'], vel: 0.8 },
    {
      kind: 'tune',
      inst: Inst.lead,
      layer: 0,
      vel: 0.7,
      tune: [
        'B5:6 G5:2 E5:8',
        'G5:4 F#5:4 E5:8',
        'E5:6 G5:2 C6:8',
        'A5:4 F#5:4 D5:8',
        'B5:6 A5:2 G5:8',
        'A5:4 C6:4 E6:8',
        'G5:4 E5:4 C5:8',
        'F#5:4 A5:4 D6:8',
        'E6:8 C6:4 G5:4',
        'D6:8 A5:4 F#5:4',
        'E5:4 G5:4 B5:8',
        'C6:8 A5:8',
        'G5:6 E5:2 G5:8',
        'A5:6 F#5:2 A5:8',
        'G5:4 B5:4 E6:8',
        'B5:8 G5:4 E5:4',
      ],
    },
  ],
});
