import { addStrings } from '@/core/i18n';

addStrings('ko', {
  'director.wave': '{act}막 · 웨이브 {wave}',
  'director.warning': '경고!',
  'director.bossIncoming': '{name} 등장!',
  'director.eliteIncoming': '{name} 출현!',
  'director.bossDefeated': '보스 격파!',
  'director.eliteDefeated': '대장 격파!',
  'director.actClear': '{act}막 클리어!',
  'director.callNext': '다음 웨이브 호출!',
  'director.victory': '승리!',
  'director.rescued': '아홉 번째 목숨! 적 {n}마리가 물러났어요',
  'director.overflow': '적이 너무 많아요!',
  'director.synergy': '{class} 시너지 {tier}단계!',
  'director.relic': '{name} 획득!',
  'director.enrage': '{name}, 화났어요!',
  'director.ability.enrage': '더 빨라져요!',
  'director.ability.inhale': '빨아들여요! 힘이 빠져요',
  'director.ability.whirl': '소용돌이! 모두 빨라져요',
  'director.ability.splash': '첨벙! 바닥이 젖어요',
  'director.ability.lightning': '번개가 떨어져요!',
  'director.ability.vaccinate': '약효 발동! 느려지지 않아요',
  'director.hazard.wet': '젖은 칸은 공격할 수 없어요',
  'director.hazard.zap': '번개 맞은 칸은 쉬어요',
});

addStrings('en', {
  'director.wave': 'Act {act} · Wave {wave}',
  'director.warning': 'WARNING',
  'director.bossIncoming': '{name} incoming!',
  'director.eliteIncoming': '{name} appears!',
  'director.bossDefeated': 'BOSS DEFEATED',
  'director.eliteDefeated': 'ELITE DEFEATED',
  'director.actClear': 'Act {act} clear!',
  'director.callNext': 'Next wave called!',
  'director.victory': 'VICTORY',
  'director.rescued': 'Nine lives! {n} enemies backed off',
  'director.overflow': 'Too many enemies!',
  'director.synergy': '{class} synergy tier {tier}!',
  'director.relic': '{name} acquired!',
  'director.enrage': '{name} is furious!',
  'director.ability.enrage': 'Faster now!',
  'director.ability.inhale': 'Inhaling! Cats weaken',
  'director.ability.whirl': 'Whirlwind! Everyone speeds up',
  'director.ability.splash': 'Splash! The floor is wet',
  'director.ability.lightning': 'Lightning incoming!',
  'director.ability.vaccinate': 'Vaccinated! Slows are ignored',
  'director.hazard.wet': 'Wet cells cannot attack',
  'director.hazard.zap': 'Zapped cells rest',
});
