/** Player-facing lines of the missions tab, ko (해요체) and en. Keys: rt.mis.* */
import { addStrings } from '@/core/i18n';
import '../system/strings';

addStrings('ko', {
  'rt.mis.tab.daily': '일일',
  'rt.mis.tab.weekly': '주간',
  'rt.mis.daily.title': '오늘의 상자',
  'rt.mis.daily.list': '오늘 할 일',
  'rt.mis.go': '가기',
  'rt.mis.pts': '+{n}점',
  'rt.mis.weekly.title': '이번 주 할 일',
  'rt.mis.weekly.chest': '주간 상자',
  'rt.mis.weekly.count': '{n}/{max}개 받음',
  'rt.mis.cup.title': '주간 컵',
  'rt.mis.cup.sub': '이번 주 일일 도전에서 하루 최고 웨이브를 더해요.',
  'rt.mis.cup.score': '합계 {n}웨이브',
  'rt.mis.cup.play': '일일 도전하러 가기',
  'rt.mis.endless.title': '무한 모드',
  'rt.mis.endless.sub': '이번 주 최고 웨이브로 상자를 받아요.',
  'rt.mis.endless.best': '역대 최고 {best}웨이브',
  'rt.mis.endless.play': '무한 모드 가기',
  'rt.mis.tier.progress': '{cur}/{need}',
  'rt.mis.day.0': '월',
  'rt.mis.day.1': '화',
  'rt.mis.day.2': '수',
  'rt.mis.day.3': '목',
  'rt.mis.day.4': '금',
  'rt.mis.day.5': '토',
  'rt.mis.day.6': '일',
});

addStrings('en', {
  'rt.mis.tab.daily': 'Daily',
  'rt.mis.tab.weekly': 'Weekly',
  'rt.mis.daily.title': 'Daily chest',
  'rt.mis.daily.list': 'To do today',
  'rt.mis.go': 'Go',
  'rt.mis.pts': '+{n} pts',
  'rt.mis.weekly.title': 'To do this week',
  'rt.mis.weekly.chest': 'Weekly chest',
  'rt.mis.weekly.count': '{n}/{max} claimed',
  'rt.mis.cup.title': 'Weekly cup',
  'rt.mis.cup.sub': 'Add up your best daily-challenge wave of each day this week.',
  'rt.mis.cup.score': 'Total {n} waves',
  'rt.mis.cup.play': 'Play the daily challenge',
  'rt.mis.endless.title': 'Endless mode',
  'rt.mis.endless.sub': 'Your best wave this week earns chests.',
  'rt.mis.endless.best': 'Best ever: wave {best}',
  'rt.mis.endless.play': 'Go to endless mode',
  'rt.mis.tier.progress': '{cur}/{need}',
  'rt.mis.day.0': 'Mon',
  'rt.mis.day.1': 'Tue',
  'rt.mis.day.2': 'Wed',
  'rt.mis.day.3': 'Thu',
  'rt.mis.day.4': 'Fri',
  'rt.mis.day.5': 'Sat',
  'rt.mis.day.6': 'Sun',
});
