import { addStrings } from '@/core/i18n';

addStrings('ko', {
  'cats.filter.all': '전체',
  'cats.merge': '합성',
  'cats.awaken': '각성',
  'cats.max': '최고',
  'cats.lv': 'Lv.{n}',
  'cats.wild.title': '만능 카드',
  'cats.line.merge': '{a} 둘을 합치면 {b}이(가) 돼요.',
  'cats.line.awaken': '{a}은(는) 각성하면 {b}이(가) 돼요.',
  'cats.line.guardian': '{a}을(를) 각성하면 {b}이(가) 돼요.',
  'cats.stamp': '레벨 업!',
  'cats.unit.title': '고양이 정보',
  'cats.unit.line': '합성 줄',
  'cats.unit.stats': '능력치',
  'cats.unit.skill': '특기',
  'cats.unit.perks': '레벨 특전',
  'cats.unit.cards': '강화 카드',
  'cats.unit.levelUp': '레벨 업',
  'cats.unit.maxed': '최고 레벨',
  'cats.unit.toLegendary': '{unit} 강화하러 가기',
  'cats.unit.guardianNote': '수호신은 대왕 {unit}의 레벨을 따라가요. 대왕을 강화하면 함께 강해져요.',
  'cats.unit.cardsLine': '가진 카드 {own}장 · 필요 {need}장',
  'cats.unit.wildLine': '만능 카드 {n}장으로 모자란 {m}장을 채워요.',
  'cats.unit.wildHave': '만능 카드 {n}장을 갖고 있어요.',
  'cats.unit.needMore': '카드가 {n}장 더 필요해요.',
  'cats.unit.maxLine': '더 올릴 곳이 없어요. 남는 카드는 골드로 바뀌어요.',
  'cats.unit.perkAt': 'Lv.{n}',
  'cats.stat.damage': '피해',
  'cats.stat.interval': '공격 간격',
  'cats.stat.range': '사거리',
  'cats.stat.crit': '치명타',
  'cats.stat.sec': '{n}초',
  'cats.err.cards': '카드가 {n}장 모자라요. 상자에서 더 모아 봐요.',
  'cats.err.gold': '골드가 {n} 모자라요. 전투에서 모아 볼까요?',
  'cats.err.goBattle': '전투하러 가기',
  'cats.err.goShop': '상점 가기',
  'cats.err.later': '나중에',
  'cats.err.goldTitle': '골드가 모자라요',
  'cats.err.cardsTitle': '카드가 모자라요',
});

addStrings('en', {
  'cats.filter.all': 'All',
  'cats.merge': 'Merge',
  'cats.awaken': 'Awaken',
  'cats.max': 'MAX',
  'cats.lv': 'Lv.{n}',
  'cats.wild.title': 'Wild cards',
  'cats.line.merge': 'Two {a} merge into {b}.',
  'cats.line.awaken': '{a} awakens into {b}.',
  'cats.line.guardian': 'Awaken {a} to get {b}.',
  'cats.stamp': 'Level up!',
  'cats.unit.title': 'Cat info',
  'cats.unit.line': 'Merge line',
  'cats.unit.stats': 'Stats',
  'cats.unit.skill': 'Skill',
  'cats.unit.perks': 'Level perks',
  'cats.unit.cards': 'Upgrade cards',
  'cats.unit.levelUp': 'Level up',
  'cats.unit.maxed': 'Max level',
  'cats.unit.toLegendary': 'Upgrade {unit}',
  'cats.unit.guardianNote': 'A Guardian follows the level of its King, {unit}. Upgrade the King and both grow.',
  'cats.unit.cardsLine': 'You have {own} · need {need}',
  'cats.unit.wildLine': '{n} wild cards cover the missing {m}.',
  'cats.unit.wildHave': 'You have {n} wild cards.',
  'cats.unit.needMore': '{n} more cards needed.',
  'cats.unit.maxLine': 'Nothing left to upgrade. Extra cards turn into gold.',
  'cats.unit.perkAt': 'Lv.{n}',
  'cats.stat.damage': 'Damage',
  'cats.stat.interval': 'Attack gap',
  'cats.stat.range': 'Range',
  'cats.stat.crit': 'Crit',
  'cats.stat.sec': '{n}s',
  'cats.err.cards': '{n} more cards needed. Collect them from chests.',
  'cats.err.gold': 'You need {n} more gold. Earn some in battle?',
  'cats.err.goBattle': 'Go to battle',
  'cats.err.goShop': 'Open shop',
  'cats.err.later': 'Later',
  'cats.err.goldTitle': 'Not enough gold',
  'cats.err.cardsTitle': 'Not enough cards',
});
